(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const on=(el,e,fn)=>{const n=typeof el==="string"?$(el):el;if(n)n.addEventListener(e,fn);return n};
const setText=(s,v)=>{const e=$(s);if(e)e.textContent=v??""},setVal=(s,v)=>{const e=$(s);if(e&&document.activeElement!==e)e.value=v??""};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const fmt=t=>{const m=Math.floor(t/60),s=Math.floor(t%60);return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")};

const canvas=$("#stage"),ctx=canvas.getContext("2d"),videoCanvas=$("#videoStage"),videoCtx=videoCanvas.getContext("2d");
let project=MEPStorage.load()||MEPModel.project("Untitled Project"),short=null,scene=null,selectedId=null,selectedBubbleId=null,time=0,playing=false,lastFrame=0,drag=null,editPreview=null,graphicDraft=null,cloudReady=false,cloudTimer=null,exporting=false;
const imageCache=new Map();
let voiceRecorder=null,voiceChunks=[],voiceStream=null,voiceRecordStarted=0,activeVoicePreview=null;
const voiceAssetFor=sh=>(project.assets||[]).find(a=>a.id===sh?.voice?.assetId);
function wholeNarration(sh=short){return(sh?.scenes||[]).map(s=>s.script||"").filter(Boolean).join(" ")}
function dataUrlToBuffer(url){return fetch(url).then(r=>r.arrayBuffer())}
function distortionCurve(amount=0){const n=2048,a=Math.max(0,amount)*80,curve=new Float32Array(n);for(let i=0;i<n;i++){const x=i*2/n-1;curve[i]=a?((3+a)*x*20*Math.PI/180)/(Math.PI+a*Math.abs(x)):x}return curve}
async function buildVoiceGraph(sh,{monitor=false}={}){
 const asset=voiceAssetFor(sh);if(!asset?.dataUrl)return null;const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;const ac=new A(),buf=await ac.decodeAudioData(await dataUrlToBuffer(asset.dataUrl)),src=ac.createBufferSource(),v=sh.voice||{};src.buffer=buf;src.playbackRate.value=Number(v.speed)||1;src.detune.value=(Number(v.pitchSemitones)||0)*100;
 const bass=ac.createBiquadFilter();bass.type="lowshelf";bass.frequency.value=180;bass.gain.value=Number(v.bass)||0;
 const mid=ac.createBiquadFilter();mid.type="peaking";mid.frequency.value=1100;mid.Q.value=.85;mid.gain.value=Number(v.mid)||0;
 const presence=ac.createBiquadFilter();presence.type="peaking";presence.frequency.value=3200;presence.Q.value=1;presence.gain.value=Number(v.presence)||0;
 const treble=ac.createBiquadFilter();treble.type="highshelf";treble.frequency.value=5200;treble.gain.value=Number(v.treble)||0;
 const grit=ac.createWaveShaper();grit.curve=distortionCurve(Number(v.grit)||0);grit.oversample="4x";
 const comp=ac.createDynamicsCompressor(),amt=Math.max(0,Math.min(1,Number(v.compression)||0));comp.threshold.value=-6-amt*24;comp.knee.value=18;comp.ratio.value=1+amt*11;comp.attack.value=.004;comp.release.value=.24;
 const gain=ac.createGain();gain.gain.value=Number(v.gain)||1;src.connect(bass).connect(mid).connect(presence).connect(treble).connect(grit).connect(comp).connect(gain);
 const dest=ac.createMediaStreamDestination(),dry=ac.createGain();dry.gain.value=1;gain.connect(dry).connect(dest);if(monitor)dry.connect(ac.destination);
 const echo=Math.max(0,Math.min(.65,Number(v.echo)||0));if(echo>0){const delay=ac.createDelay(.7),feedback=ac.createGain(),wet=ac.createGain();delay.delayTime.value=.16;feedback.gain.value=Math.min(.45,echo*.65);wet.gain.value=echo*.65;gain.connect(delay);delay.connect(wet).connect(dest);delay.connect(feedback).connect(delay);if(monitor)wet.connect(ac.destination)}
 return{ac,src,track:dest.stream.getAudioTracks()[0],duration:buf.duration}
}
function refreshRefs(){MEPModel.syncAlias(project);short=MEPModel.activeShort(project);scene=MEPModel.activeScene(project);selectedId=scene?.characters?.some(c=>c.id===selectedId)?selectedId:(scene?.characters?.[0]?.id||null);selectedBubbleId=null;time=0;playing=false;editPreview=null;applyCanvasSize()}
function applyCanvasSize(){if(!short)return;for(const c of [canvas,videoCanvas]){c.width=short.width||720;c.height=short.height||1280}document.documentElement.style.setProperty("--stage-ratio",(short.width||720)+"/"+(short.height||1280))}
refreshRefs();

const selected=()=>scene?.characters?.find(c=>c.id===selectedId)||null;
const selectedBubble=()=>scene?.bubbles?.find(b=>b.id===selectedBubbleId)||null;
const assetById=id=>(project.assets||[]).find(a=>a.id===id)||null;
const visibleBubbles=(s,t)=>(s.bubbles||[]).filter(b=>t>=(b.startTime??0)&&t<=(b.endTime??s.duration));
const shortIndex=()=>Math.max(0,project.shorts.findIndex(s=>s.id===short.id));
const sceneIndex=()=>Math.max(0,short.scenes.findIndex(s=>s.id===scene.id));

function imageForAsset(asset){if(!asset?.dataUrl)return null;if(imageCache.has(asset.id))return imageCache.get(asset.id);const im=new Image();im.src=asset.dataUrl;imageCache.set(asset.id,im);im.onload=()=>render();return im}
function drawImageFit(context,img,bg={}){if(!img?.complete)return;const cw=context.canvas.width,ch=context.canvas.height,iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height;if(!iw||!ih)return;const fit=bg.fit||"cover",opacity=bg.opacity??1,userScale=Math.max(.25,Number(bg.scale)||1),panX=Number(bg.panX)||0,panY=Number(bg.panY)||0,brightness=Math.max(.2,Number(bg.brightness)||1),blur=Math.max(0,Number(bg.blur)||0);context.save();context.globalAlpha=Math.max(0,Math.min(1,opacity));context.filter="brightness("+brightness+") blur("+blur+"px)";if(fit==="stretch"){const w=cw*userScale,h=ch*userScale;context.drawImage(img,(cw-w)/2+panX,(ch-h)/2+panY,w,h)}else{const base=fit==="contain"?Math.min(cw/iw,ch/ih):Math.max(cw/iw,ch/ih),scale=base*userScale,w=iw*scale,h=ih*scale;context.drawImage(img,(cw-w)/2+panX,(ch-h)/2+panY,w,h)}context.restore()}
function renderBackground(context,s,t){const bg=MEPModel.backgroundAt(s,t);MEPRenderer.drawBackground(context,bg.preset||"europeMap",context.canvas.width,context.canvas.height);if(bg.mode==="image"&&bg.assetId){const im=imageForAsset(assetById(bg.assetId));if(im)drawImageFit(context,im,bg)}return bg}
function stateFor(ch){if(!playing&&editPreview?.id===ch.id&&Math.abs(editPreview.time-time)<.001)return MEPModel.capture(ch);return(time>0||playing)?MEPModel.stateAt(ch,time):MEPModel.capture(ch)}
function renderScene(context,s,t,{selectable=false}={}){context.save();context.clearRect(0,0,context.canvas.width,context.canvas.height);const cam=s.camera||{x:context.canvas.width/2,y:context.canvas.height/2,zoom:1};context.translate(context.canvas.width/2,context.canvas.height/2);context.scale(cam.zoom||1,cam.zoom||1);context.translate(-(cam.x??context.canvas.width/2),-(cam.y??context.canvas.height/2));renderBackground(context,s,t);MEPRenderer.drawGraphics(context,s.graphics||[],t);[...(s.characters||[])].sort((a,b)=>(a.layer||0)-(b.layer||0)).forEach(ch=>MEPRenderer.drawCharacter(context,selectable&&s.id===scene.id?stateFor(ch):MEPModel.stateAt(ch,t),ch,selectable&&ch.id===selectedId));context.restore();visibleBubbles(s,t).forEach(b=>MEPRenderer.drawBubble(context,b))}
function render(){renderScene(ctx,scene,time,{selectable:true});setText("#timeLabel",time.toFixed(2)+" / "+scene.duration.toFixed(2)+"s");setVal("#scrubber",time)}

function changed({cloud=true}={}){short.updatedAt=new Date().toISOString();MEPModel.syncAlias(project);MEPStorage.save(project);setText("#saveStatus",cloudReady?"Saving…":"Local ✓");drawTimeline();render();syncBuddy();if(cloud&&cloudReady){clearTimeout(cloudTimer);cloudTimer=setTimeout(async()=>{try{await MEPStorage.saveCloud(project);setText("#saveStatus","Firestore ✓")}catch(e){console.warn(e);setText("#saveStatus","Local ✓")}},1800)}}
function materializeSelected(){const ch=selected();if(!ch)return null;if(time>0&&!(editPreview?.id===ch.id&&Math.abs(editPreview.time-time)<.001)){const st=MEPModel.stateAt(ch,time);Object.assign(ch,{x:st.x,y:st.y,scale:st.scale,rotation:st.rotation||0,facing:st.facing});ch.visual.mouthOpen=!!st.mouthOpen;editPreview={id:ch.id,time}}return ch}
function activateShort(id){MEPModel.setActiveShort(project,id);refreshRefs();syncUI()}
function activateScene(id){MEPModel.setActiveScene(project,id);scene=MEPModel.activeScene(project);selectedId=scene.characters?.[0]?.id||null;selectedBubbleId=null;time=0;playing=false;editPreview=null;syncUI()}
function setYear(y){y=Math.max(1600,Math.min(2026,Math.round(Number(y)||1944)));short.year=y;short.era=MEPModel.yearToEra(y);for(const s of short.scenes)for(const ch of s.characters||[])if(ch.visual?.followProjectYear!==false)ch.visual.historicalYear=y;MEPModel.syncAlias(project);changed();syncUI()}

function syncShortUI(){
 $("#shortSelect").innerHTML=project.shorts.map((s,i)=>'<option value="'+s.id+'">'+(i+1)+'. '+esc(s.title)+'</option>').join("");setVal("#shortSelect",short.id);$("#shortList").innerHTML=project.shorts.map((s,i)=>'<button class="sceneCard '+(s.id===short.id?"active":"")+'" data-short-card="'+s.id+'"><strong>'+(i+1)+'. '+esc(s.title)+'</strong><small>'+MEPModel.shortDuration(s).toFixed(0)+'s · '+s.scenes.length+' scenes</small></button>').join("");$("[data-short-card]").forEach(b=>on(b,"click",()=>activateShort(b.dataset.shortCard)));setVal("#shortTitle",short.title);setVal("#uploadTitle",short.title);setVal("#projectYear",short.year);setVal("#yearSlider",short.year);setText("#eraBadge",short.era);setText("#shortDuration",MEPModel.shortDuration(short).toFixed(0)+"s");setVal("#shortDescription",short.description||"");setVal("#shortHashtags",(short.hashtags||[]).join(" "))
}
function syncSceneUI(){
 $("#sceneSelect").innerHTML=short.scenes.map(s=>'<option value="'+s.id+'">'+esc(s.name)+'</option>').join("");setVal("#sceneSelect",scene.id);
 $("#sceneBoard").innerHTML=short.scenes.map((s,i)=>'<button class="sceneCard '+(s.id===scene.id?"active":"")+'" data-scene="'+s.id+'"><strong>'+(i+1)+'. '+esc(s.name)+'</strong><small>'+s.duration.toFixed(1)+'s · '+(s.characters?.length||0)+' flags · '+(s.graphics?.length||0)+' graphics</small></button>').join("");$$("[data-scene]").forEach(b=>on(b,"click",()=>activateScene(b.dataset.scene)));
 setVal("#sceneTransition",scene.transition?.type||"cut");setVal("#duration",scene.duration);setVal("#fps",short.fps||30)
}
function syncBackgroundUI(){
 const bg=MEPModel.backgroundAt(scene,time);$("#backgroundPreset").innerHTML=Object.entries(MEPModel.BACKGROUNDS).map(([k,v])=>'<option value="'+k+'">'+esc(v.name)+'</option>').join("");setVal("#backgroundPreset",bg.preset);setVal("#backgroundFit",bg.fit||"cover");setVal("#backgroundPanX",bg.panX||0);setVal("#backgroundPanY",bg.panY||0);setVal("#backgroundScale",bg.scale||1);setVal("#backgroundOpacity",bg.opacity??1);setVal("#backgroundBrightness",bg.brightness??1);setVal("#backgroundBlur",bg.blur||0);setText("#backgroundModeLabel",bg.mode==="image"?"Image background":"Drawn background");const a=assetById(bg.assetId);setText("#backgroundAssetLabel",a?a.name:"");
 $("#backgroundKeyframes").innerHTML=(scene.background.keyframes||[]).map((k,i)=>'<div class="characterItem"><button data-bg-time="'+k.time+'">'+k.time.toFixed(1)+'s · '+esc(k.preset||k.mode)+'</button><button data-bg-del="'+i+'" class="danger">×</button></div>').join("");$$("[data-bg-time]").forEach(b=>on(b,"click",()=>{time=Number(b.dataset.bgTime);render();syncBackgroundUI()}));$$("[data-bg-del]").forEach(b=>on(b,"click",()=>{scene.background.keyframes.splice(Number(b.dataset.bgDel),1);changed();syncBackgroundUI()}))
}
function syncGraphicsUI(){
 $("#graphicType").innerHTML=Object.entries(MEPModel.GRAPHIC_TYPES).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join("");setVal("#graphicEnd",Math.min(scene.duration,Number($("#graphicEnd")?.value)||scene.duration));
 $("#graphicsList").innerHTML=(scene.graphics||[]).map((g,i)=>'<div class="characterItem"><button data-graphic-time="'+(g.startTime||0)+'"><strong>'+esc(MEPModel.GRAPHIC_TYPES[g.type]||g.type)+'</strong><small>'+esc(g.label||"")+' · '+Number(g.startTime||0).toFixed(1)+'–'+Number(g.endTime||scene.duration).toFixed(1)+'s</small></button><button data-graphic-del="'+i+'" class="danger">×</button></div>').join("");$$("[data-graphic-time]").forEach(b=>on(b,"click",()=>{time=Number(b.dataset.graphicTime);render()}));$$("[data-graphic-del]").forEach(b=>on(b,"click",()=>{scene.graphics.splice(Number(b.dataset.graphicDel),1);changed();syncGraphicsUI()}))
}
function fillOptions(){
 $("#characterShape").innerHTML=Object.entries(MEPModel.SHAPES).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join("");$("#expression").innerHTML=MEPModel.EXPRESSIONS.map(x=>'<option value="'+x+'">'+x[0].toUpperCase()+x.slice(1)+'</option>').join("");$("#characterProp").innerHTML=Object.entries(MEPModel.PROPS).map(([k,v])=>'<option value="'+k+'">'+v.name+'</option>').join("");$("#animationClip").innerHTML=Object.entries(MEPModel.ANIMATION_CLIPS).map(([k,v])=>'<option value="'+k+'">'+v.name+'</option>').join("");$("#keyframeEasing").innerHTML=Object.entries(MEPModel.EASINGS).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join("");$("#bubbleStyle").innerHTML=Object.entries(MEPModel.BUBBLE_STYLES).map(([k,v])=>'<option value="'+k+'">'+v.name+'</option>').join("")
}
function syncCharactersUI(){
 const era=MEPModel.ERA_CHARACTER_PRESETS[short.era]||Object.keys(MEPModel.CHARACTER_PRESETS);$("#characterPreset").innerHTML=era.filter(k=>MEPModel.CHARACTER_PRESETS[k]).map(k=>'<option value="'+k+'">'+esc(MEPModel.CHARACTER_PRESETS[k].name)+'</option>').join("");
 const quick=["noveriaHost","germanEmpire","britain1914","usa1941","japan1941","soviet1945"];$("#quickPresetGrid").innerHTML=quick.filter(k=>MEPModel.CHARACTER_PRESETS[k]).map(k=>'<button data-quick="'+k+'">'+esc(MEPModel.CHARACTER_PRESETS[k].name)+'</button>').join("");$$("[data-quick]").forEach(b=>on(b,"click",()=>addPreset(b.dataset.quick)));
 $("#characterList").innerHTML=(scene.characters||[]).map(ch=>{const fl=MEPHistoryFlags.resolve(ch.visual.countryCode||"US",ch.visual.historicalYear||short.year,ch.visual.flagVariant||"auto");return'<button class="characterItem '+(ch.id===selectedId?"active":"")+'" data-char="'+ch.id+'"><strong>'+esc(ch.name)+'</strong><small>'+esc(ch.visual.shape)+' · '+esc(fl.label)+'</small></button>'}).join("");$$("[data-char]").forEach(b=>on(b,"click",()=>{selectedId=b.dataset.char;editPreview=null;syncCharactersUI();render()}));
 const ch=selected();if(!ch){["#charName","#countryCode","#flagLabel"].forEach(x=>setVal(x,""));return}setVal("#charName",ch.name);setVal("#characterShape",ch.visual.shape);setVal("#expression",ch.visual.expression||"neutral");setVal("#mouthMode",ch.visual.mouthEnabled===false?"off":"on");setVal("#hatStyle",ch.visual.hat||"none");setVal("#hairStyle",ch.visual.hairStyle||"none");setVal("#characterProp",ch.prop||"none");setVal("#charX",Math.round(ch.x));setVal("#charY",Math.round(ch.y));setVal("#charScale",ch.scale);setVal("#charRotation",ch.rotation||0);const opts=MEPHistoryFlags.options(short.year);$("#countryCode").innerHTML=opts.map(o=>'<option value="'+o.code+'">'+(o.historical?"★ ":"")+esc(o.name)+'</option>').join("");setVal("#countryCode",ch.visual.countryCode||"US");const fl=MEPHistoryFlags.resolve(ch.visual.countryCode||"US",ch.visual.historicalYear||short.year,ch.visual.flagVariant||"auto");setText("#flagLabel",fl.label+" · "+(ch.visual.historicalYear||short.year))
}
function syncScripts(){setVal("#sceneScript",scene.script||"");setVal("#sceneCaption",scene.caption||"");setVal("#sceneNotes",scene.notes||"")}
function syncBubbles(){
 $("#bubbleList").innerHTML=(scene.bubbles||[]).map(b=>'<button class="bubbleItem '+(b.id===selectedBubbleId?"active":"")+'" data-bubble="'+b.id+'">'+esc(b.text||"Bubble")+'</button>').join("");$$("[data-bubble]").forEach(b=>on(b,"click",()=>{selectedBubbleId=b.dataset.bubble;syncBubbles()}));const b=selectedBubble();if(b){setVal("#bubbleText",b.text);setVal("#bubbleStyle",b.style||"speech");setVal("#bubbleStart",b.startTime??0);setVal("#bubbleEnd",b.endTime??scene.duration)}else{setVal("#bubbleText","");setVal("#bubbleStart",time);setVal("#bubbleEnd",Math.min(scene.duration,time+3))}
}
function populateChromeVoices(){
 const el=$("#chromeVoice");if(!el||!window.speechSynthesis)return;const voices=speechSynthesis.getVoices();if(!voices.length)return;const current=short?.voice?.chromeVoice||"";el.innerHTML=voices.map(v=>'<option value="'+esc(v.name)+'">'+esc(v.name)+' · '+esc(v.lang)+'</option>').join("");if(current&&voices.some(v=>v.name===current))el.value=current;else if(!short.voice.chromeVoice){const preferred=voices.find(v=>/^en-US/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||voices[0];short.voice.chromeVoice=preferred?.name||"";el.value=short.voice.chromeVoice}
}
function syncVoiceUI(){
 short.voice=short.voice||MEPModel.short().voice;const v=short.voice,asset=voiceAssetFor(short);setVal("#voiceSource",v.source||"mic");setVal("#ttsRate",v.ttsRate??1);setText("#ttsRateOut",Number(v.ttsRate??1).toFixed(2));setVal("#ttsPitch",v.ttsPitch??1);setText("#ttsPitchOut",Number(v.ttsPitch??1).toFixed(2));setVal("#voicePitch",v.pitchSemitones??0);setText("#voicePitchOut",(Number(v.pitchSemitones??0)>0?"+":"")+Number(v.pitchSemitones??0)+" st");setVal("#voiceSpeed",v.speed??1);setText("#voiceSpeedOut",Number(v.speed??1).toFixed(2)+"x");setVal("#eqBass",v.bass??0);setText("#eqBassOut",(Number(v.bass??0)>0?"+":"")+Number(v.bass??0)+" dB");setVal("#eqMid",v.mid??0);setText("#eqMidOut",(Number(v.mid??0)>0?"+":"")+Number(v.mid??0)+" dB");setVal("#eqTreble",v.treble??0);setText("#eqTrebleOut",(Number(v.treble??0)>0?"+":"")+Number(v.treble??0)+" dB");setVal("#eqPresence",v.presence??2);setText("#eqPresenceOut",(Number(v.presence??2)>0?"+":"")+Number(v.presence??2)+" dB");setVal("#voiceCompression",v.compression??.35);setText("#voiceCompressionOut",Math.round(Number(v.compression??.35)*100)+"%");setVal("#voiceEcho",v.echo??0);setText("#voiceEchoOut",Math.round(Number(v.echo??0)*100)+"%");setVal("#voiceGrit",v.grit??0);setText("#voiceGritOut",Math.round(Number(v.grit??0)*100)+"%");setVal("#voiceGain",v.gain??1);setText("#voiceGainOut",Number(v.gain??1).toFixed(2)+"x");setText("#voiceStatus",asset?(asset.durationSeconds?("Recorded voiceover · "+asset.durationSeconds.toFixed(1)+"s"):"Recorded voiceover ready"):"No recorded voiceover yet.");populateChromeVoices()
}
function syncBuddy(){setText("#helperYear",short.year+" · "+short.era);setText("#helperScene",scene.name);setText("#helperCharacter",selected()?.name||"No character");setText("#helperStatus",cloudReady?"Firestore ready":"Floating around")}
function syncUI(){applyCanvasSize();setVal("#projectName",project.name);fillOptions();syncShortUI();syncSceneUI();syncBackgroundUI();syncGraphicsUI();syncCharactersUI();syncScripts();syncBubbles();syncVoiceUI();$("#scrubber").max=scene.duration;setVal("#scrubber",Math.min(time,scene.duration));drawTimeline();render();syncBuddy();setText("#bootStatus","Ready · "+project.shorts.length+" short"+(project.shorts.length===1?"":"s")+" · recent project autosave on");$("#bootStatus").className="bootStatus ready"}

function drawTimeline(){const dur=Math.max(.01,scene.duration),bg='<div class="track"><div class="trackName">Background</div><div class="trackLane">'+(scene.background.keyframes||[]).map(k=>'<span class="bgKey" data-bgt="'+k.time+'" style="left:'+(k.time/dur*100)+'%"></span>').join("")+'</div></div>',gr='<div class="track"><div class="trackName">Graphics</div><div class="trackLane">'+(scene.graphics||[]).map(g=>'<span class="bubbleRange" data-gt="'+(g.startTime||0)+'" style="left:'+((g.startTime||0)/dur*100)+'%;width:'+Math.max(.8,((g.endTime??dur)-(g.startTime||0))/dur*100)+'%" title="'+esc(g.label||g.type)+'"></span>').join("")+'</div></div>',chars=(scene.characters||[]).map(ch=>'<div class="track"><div class="trackName">'+esc(ch.name)+'</div><div class="trackLane">'+(ch.keyframes||[]).map(k=>'<span class="key" data-kchar="'+ch.id+'" data-ktime="'+k.time+'" style="left:'+(k.time/dur*100)+'%"></span>').join("")+'</div></div>').join("");$("#timeline").innerHTML=bg+gr+chars;$$("[data-bgt]").forEach(x=>on(x,"click",()=>{time=Number(x.dataset.bgt);render()}));$$("[data-gt]").forEach(x=>on(x,"click",()=>{time=Number(x.dataset.gt);render()}));$$("[data-kchar]").forEach(x=>on(x,"click",()=>{selectedId=x.dataset.kchar;time=Number(x.dataset.ktime);syncCharactersUI();render()}))}
function addPreset(key){const p=MEPModel.CHARACTER_PRESETS[key]||MEPModel.CHARACTER_PRESETS.noveriaHost,ch=MEPModel.character(p.name,360,850,key);if(ch.visual.followProjectYear!==false)ch.visual.historicalYear=short.year;scene.characters.push(ch);selectedId=ch.id;changed();syncUI()}
function addKeyframe(){const ch=materializeSelected();if(!ch)return;const q=Math.max(0,Math.min(scene.duration,Math.round(time*100)/100)),state=MEPModel.capture(ch),ease=$("#keyframeEasing").value||"linear",old=ch.keyframes.find(k=>Math.abs(k.time-q)<.011);if(old){old.state=state;old.easing=ease}else ch.keyframes.push({id:MEPModel.id(),time:q,easing:ease,state});ch.keyframes.sort((a,b)=>a.time-b.time);editPreview=null;changed()}
function generateClip(){const ch=materializeSelected();if(!ch)return;const clip=MEPModel.ANIMATION_CLIPS[$("#animationClip").value];if(!clip)return;const duration=Math.max(.5,Number($("#clipDuration").value)||clip.duration),start=time,steps=Math.max(2,clip.scale?.length||0,clip.rotation?.length||0,clip.mouth?.length||0,clip.y?.length||0),dt=duration/(steps-1),base={x:ch.x,y:ch.y,scale:ch.scale,rotation:ch.rotation||0,facing:ch.facing,mouthOpen:!!ch.visual.mouthOpen};scene.duration=Math.max(scene.duration,start+duration);for(let i=0;i<steps;i++){const t=start+i*dt,ratio=i/(steps-1),pick=(a,d)=>a?.[Math.min(i,a.length-1)]??d;ch.x=base.x+(clip.move||0)*ratio*base.facing;ch.y=base.y+pick(clip.y,0);ch.scale=base.scale*pick(clip.scale,1);ch.rotation=base.rotation+pick(clip.rotation,0);ch.visual.mouthOpen=!!pick(clip.mouth,false);const k={id:MEPModel.id(),time:Math.round(t*100)/100,easing:i?"easeInOut":"linear",state:MEPModel.capture(ch)},old=ch.keyframes.find(x=>Math.abs(x.time-t)<.011);if(old)Object.assign(old,k);else ch.keyframes.push(k)}Object.assign(ch,base);ch.visual.mouthOpen=base.mouthOpen;ch.keyframes.sort((a,b)=>a.time-b.time);changed();syncUI()}
async function compressImage(file){const bitmap=await createImageBitmap(file),maxW=1080,maxH=1920,scale=Math.min(1,maxW/bitmap.width,maxH/bitmap.height),c=document.createElement("canvas");c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext("2d").drawImage(bitmap,0,0,c.width,c.height);let q=.8,url=c.toDataURL("image/jpeg",q);while(url.length>780000&&q>.36){q-=.08;url=c.toDataURL("image/jpeg",q)}return{id:MEPModel.id(),name:file.name.replace(/\.[^.]+$/,"")+".jpg",type:"image/jpeg",size:url.length,dataUrl:url}}
function addBackgroundKey(){const bg=MEPModel.backgroundAt(scene,time),kf={id:MEPModel.id(),time:Math.round(time*100)/100,preset:bg.preset,mode:bg.mode,assetId:bg.assetId||null,fit:bg.fit||"cover",opacity:bg.opacity??1,panX:bg.panX||0,panY:bg.panY||0,scale:bg.scale||1,brightness:bg.brightness??1,blur:bg.blur||0},old=scene.background.keyframes.find(k=>Math.abs(k.time-kf.time)<.011);if(old)Object.assign(old,kf);else scene.background.keyframes.push(kf);scene.background.keyframes.sort((a,b)=>a.time-b.time);changed();syncBackgroundUI()}

function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function worldPos(p){const cam=scene.camera||{x:canvas.width/2,y:canvas.height/2,zoom:1},z=cam.zoom||1;return{x:(p.x-canvas.width/2)/z+(cam.x??canvas.width/2),y:(p.y-canvas.height/2)/z+(cam.y??canvas.height/2)}}
function beginGraphic(){graphicDraft={type:$("#graphicType").value,label:$("#graphicLabel").value.trim(),startTime:Math.max(0,Number($("#graphicStart").value)||0),endTime:Math.min(scene.duration,Math.max(0,Number($("#graphicEnd").value)||scene.duration)),points:[]};setText("#graphicHint",graphicDraft.type==="front"?"Tap several points along the front, then Finish Line.":"Tap the canvas to place/draw "+(MEPModel.GRAPHIC_TYPES[graphicDraft.type]||graphicDraft.type)+".")}
function commitGraphic(){
 if(!graphicDraft)return;const d=graphicDraft,p=d.points;if(d.type==="front"&&p.length<2)return;
 let g={id:MEPModel.id(),type:d.type,label:d.label,startTime:d.startTime,endTime:d.endTime,color:d.type==="front"?"#a92f35":d.type==="plane"?"#2f6da1":"#d54444",fill:"#d5444433",width:8,size:34,points:p.slice()};
 if(d.type==="label"||d.type==="impact"){g.x=p[0].x;g.y=p[0].y}if(d.type==="zone"&&p.length>=2){g.points=[{x:p[0].x,y:p[0].y},{x:p[1].x,y:p[0].y},{x:p[1].x,y:p[1].y},{x:p[0].x,y:p[1].y}]}scene.graphics.push(g);graphicDraft=null;setText("#graphicHint","Graphic added. Pick another tool or edit the scene.");changed();syncGraphicsUI()
}
function handleGraphicPoint(p){if(!graphicDraft)return false;graphicDraft.points.push(worldPos(p));const t=graphicDraft.type;if(t==="label"||t==="impact")commitGraphic();else if(["arrow","route","plane","zone"].includes(t)&&graphicDraft.points.length>=2)commitGraphic();else{setText("#graphicHint","Point "+graphicDraft.points.length+" added. "+(t==="front"?"Keep tapping or press Finish Line.":"Tap the next point."));render()}return true}

on(canvas,"pointerdown",e=>{const p=pointerPos(e);if(handleGraphicPoint(p))return;const bubble=[...visibleBubbles(scene,time)].reverse().find(b=>p.x>=b.x&&p.x<=b.x+(b.width||300)&&p.y>=b.y&&p.y<=b.y+(b.height||100));if(bubble){selectedBubbleId=bubble.id;drag={type:"bubble",dx:p.x-bubble.x,dy:p.y-bubble.y};canvas.setPointerCapture(e.pointerId);syncBubbles();return}const wp=worldPos(p);let best=null,bestArea=Infinity;for(const ch of scene.characters||[]){const st=stateFor(ch),b=MEPRenderer.bounds(st,ch);if(wp.x>=b.x&&wp.x<=b.x+b.w&&wp.y>=b.y&&wp.y<=b.y+b.h&&b.w*b.h<bestArea){best=ch;bestArea=b.w*b.h}}if(best){selectedId=best.id;const ch=materializeSelected();drag={type:"char",dx:wp.x-ch.x,dy:wp.y-ch.y};canvas.setPointerCapture(e.pointerId);syncCharactersUI()}});
on(canvas,"pointermove",e=>{if(!drag)return;const p=pointerPos(e);if(drag.type==="bubble"){const b=selectedBubble();if(b){b.x=Math.max(0,Math.min(canvas.width-(b.width||300),p.x-drag.dx));b.y=Math.max(0,Math.min(canvas.height-(b.height||100),p.y-drag.dy));render()}return}const ch=selected(),wp=worldPos(p);if(ch){ch.x=wp.x-drag.dx;ch.y=wp.y-drag.dy;editPreview={id:ch.id,time};render()}});
on(canvas,"pointerup",()=>{if(drag){drag=null;changed();syncCharactersUI()}});

function cloneShort(src){const s=structuredClone(src);s.id=MEPModel.id();s.title=src.title+" Copy";s.scenes=s.scenes.map(sc=>{sc.id=MEPModel.id();sc.characters=(sc.characters||[]).map(ch=>({...ch,id:MEPModel.id(),keyframes:(ch.keyframes||[]).map(k=>({...k,id:MEPModel.id()}))}));sc.graphics=(sc.graphics||[]).map(g=>({...g,id:MEPModel.id()}));sc.bubbles=(sc.bubbles||[]).map(b=>({...b,id:MEPModel.id()}));return sc});s.activeSceneId=s.scenes[0].id;return s}
function cloneScene(src){const s=structuredClone(src);s.id=MEPModel.id();s.name=src.name+" Copy";s.characters=(s.characters||[]).map(ch=>({...ch,id:MEPModel.id(),keyframes:(ch.keyframes||[]).map(k=>({...k,id:MEPModel.id()}))}));s.graphics=(s.graphics||[]).map(g=>({...g,id:MEPModel.id()}));s.bubbles=(s.bubbles||[]).map(b=>({...b,id:MEPModel.id()}));return s}

on("#projectName","input",e=>{project.name=e.target.value;changed()});
on("#newProject","click",()=>{MEPStorage.save(project);project=MEPModel.project("Untitled Project");refreshRefs();changed({cloud:false});syncUI()});
async function openProjects(){const local=MEPStorage.listLocal();$("#localProjectList").innerHTML=local.length?local.map(x=>'<button class="cloudCard" data-local="'+x.id+'"><strong>'+esc(x.name)+'</strong><small>'+x.shortCount+' shorts · '+esc(x.updatedAt.slice(0,16).replace("T"," "))+'</small></button>').join(""):'<p>No local projects yet.</p>';$$("[data-local]").forEach(b=>on(b,"click",()=>{const p=MEPStorage.load(b.dataset.local);if(p){project=p;refreshRefs();$("#projectDialog").close();syncUI()}}));if(cloudReady){try{const cloud=await MEPStorage.listCloud();$("#cloudProjectList").innerHTML=cloud.length?cloud.map(x=>'<button class="cloudCard" data-cloud="'+x.id+'"><strong>'+esc(x.name)+'</strong><small>'+x.shortCount+' shorts</small></button>').join(""):'<p>No Firestore projects.</p>';$$("[data-cloud]").forEach(b=>on(b,"click",async()=>{project=await MEPStorage.loadCloud(b.dataset.cloud);refreshRefs();$("#projectDialog").close();syncUI()}))}catch(e){$("#cloudProjectList").innerHTML="<p>Cloud unavailable.</p>"}}else $("#cloudProjectList").innerHTML="<p>Firestore not connected yet.</p>";$("#projectDialog").showModal()}
on("#openProjects","click",openProjects);on("#closeProjectDialog","click",()=>$("#projectDialog").close());
async function loadShortPack(){const r=await fetch("presets/youtube-short-maker.mep.json",{cache:"no-store"});if(!r.ok)throw new Error("Could not load YouTube Short Maker");project=MEPModel.migrate(await r.json());refreshRefs();changed({cloud:false});syncUI()}
on("#loadShortPack","click",()=>loadShortPack().catch(e=>alert(e.message)));
on("#saveProject","click",()=>{MEPStorage.save(project);setText("#saveStatus","Local ✓")});on("#saveCloud","click",async()=>{try{await MEPStorage.saveCloud(project);cloudReady=true;setText("#saveStatus","Firestore ✓")}catch(e){alert(e.message)}});on("#exportProject","click",()=>MEPStorage.download(project));on("#importProject","change",async e=>{const f=e.target.files?.[0];if(!f)return;try{project=MEPModel.migrate(JSON.parse(await f.text()));const v=MEPModel.validateProject(project);if(!v.ok)throw new Error(v.errors.join("; "));refreshRefs();changed({cloud:false});syncUI()}catch(err){alert("Import failed: "+err.message)}e.target.value=""});

on("#shortSelect","change",e=>activateShort(e.target.value));on("#addShort","click",()=>{const sh=MEPModel.short("Untitled Short "+(project.shorts.length+1));project.shorts.push(sh);project.activeShortId=sh.id;refreshRefs();changed();syncUI()});on("#duplicateShort","click",()=>{const sh=cloneShort(short);project.shorts.splice(shortIndex()+1,0,sh);project.activeShortId=sh.id;refreshRefs();changed();syncUI()});on("#deleteShort","click",()=>{if(project.shorts.length<=1)return alert("A project needs at least one short.");if(!confirm("Delete this short?"))return;const i=shortIndex();project.shorts.splice(i,1);project.activeShortId=project.shorts[Math.min(i,project.shorts.length-1)].id;refreshRefs();changed();syncUI()});
on("#shortTitle","input",e=>{short.title=e.target.value;changed();syncShortUI()});on("#uploadTitle","input",e=>{short.title=e.target.value;changed();syncShortUI()});on("#shortDescription","input",e=>{short.description=e.target.value;changed()});on("#shortHashtags","input",e=>{short.hashtags=e.target.value.split(/\s+/).filter(Boolean);changed()});on("#projectYear","change",e=>setYear(e.target.value));on("#yearSlider","input",e=>setYear(e.target.value));

on("#sceneSelect","change",e=>activateScene(e.target.value));on("#prevScene","click",()=>activateScene(short.scenes[Math.max(0,sceneIndex()-1)].id));on("#nextScene","click",()=>activateScene(short.scenes[Math.min(short.scenes.length-1,sceneIndex()+1)].id));on("#addScene","click",()=>{const s=MEPModel.scene("Scene "+(short.scenes.length+1),7);short.scenes.push(s);short.activeSceneId=s.id;refreshRefs();changed();syncUI()});on("#duplicateScene","click",()=>{const s=cloneScene(scene);short.scenes.splice(sceneIndex()+1,0,s);short.activeSceneId=s.id;refreshRefs();changed();syncUI()});on("#deleteScene","click",()=>{if(short.scenes.length<=1)return alert("A short needs at least one scene.");if(!confirm("Delete this scene?"))return;const i=sceneIndex();short.scenes.splice(i,1);short.activeSceneId=short.scenes[Math.min(i,short.scenes.length-1)].id;refreshRefs();changed();syncUI()});on("#sceneTransition","change",e=>{scene.transition.type=e.target.value;changed()});on("#duration","change",e=>{scene.duration=Math.max(1,Math.min(60,Number(e.target.value)||7));time=Math.min(time,scene.duration);changed();syncUI()});on("#fps","change",e=>{short.fps=Number(e.target.value)||30;changed()});

on("#backgroundPreset","change",e=>{scene.background.preset=e.target.value;if(scene.background.mode!=="image")scene.background.mode="preset";changed();syncBackgroundUI()});function cycleSelect(id,d){const e=$(id);if(!e.options.length)return;e.selectedIndex=(e.selectedIndex+d+e.options.length)%e.options.length;e.dispatchEvent(new Event("change"))}on("#prevBackground","click",()=>cycleSelect("#backgroundPreset",-1));on("#nextBackground","click",()=>cycleSelect("#backgroundPreset",1));on("#useDrawnBackground","click",()=>{scene.background.mode="preset";scene.background.assetId=null;changed();syncBackgroundUI()});on("#backgroundFit","change",e=>{scene.background.fit=e.target.value;changed()});[["backgroundPanX","panX"],["backgroundPanY","panY"],["backgroundScale","scale"],["backgroundOpacity","opacity"],["backgroundBrightness","brightness"],["backgroundBlur","blur"]].forEach(([id,key])=>on("#"+id,"change",e=>{scene.background[key]=Number(e.target.value);changed();syncBackgroundUI()}));on("#backgroundUpload","change",async e=>{const f=e.target.files?.[0];if(!f)return;try{const a=await compressImage(f);project.assets.push(a);scene.background.mode="image";scene.background.assetId=a.id;changed();syncBackgroundUI()}catch(err){alert(err.message)}e.target.value=""});on("#addBackgroundKeyframe","click",addBackgroundKey);

on("#drawGraphic","click",beginGraphic);on("#finishGraphic","click",()=>{if(graphicDraft?.type==="front")commitGraphic();else setText("#graphicHint","Finish Line is only needed for a multi-point front line.")});

on("#addPresetCharacter","click",()=>addPreset($("#characterPreset").value));on("#addHost","click",()=>addPreset("noveriaHost"));on("#openCharacterGallery","click",()=>{const entries=Object.entries(MEPModel.CHARACTER_PRESETS);$("#characterGalleryList").innerHTML=entries.map(([k,p])=>'<button class="characterCard" data-gallery="'+k+'"><strong>'+esc(p.name)+'</strong><span>'+esc(p.era)+'</span><small>'+esc(p.shape)+' · '+esc(MEPHistoryFlags.resolve(p.countryCode,p.year).label)+'</small></button>').join("");$$("[data-gallery]").forEach(b=>on(b,"click",()=>{addPreset(b.dataset.gallery);$("#characterGalleryDialog").close()}));$("#characterGalleryDialog").showModal()});on("#closeCharacterGallery","click",()=>$("#characterGalleryDialog").close());
on("#charName","input",e=>{const ch=selected();if(ch){ch.name=e.target.value;changed()}});on("#characterShape","change",e=>{const ch=materializeSelected();if(ch){ch.visual.shape=e.target.value;changed()}});on("#countryCode","change",e=>{const ch=materializeSelected();if(ch){ch.visual.countryCode=e.target.value;if(ch.visual.followProjectYear!==false)ch.visual.historicalYear=short.year;changed();syncCharactersUI()}});on("#expression","change",e=>{const ch=materializeSelected();if(ch){ch.visual.expression=e.target.value;changed()}});on("#mouthMode","change",e=>{const ch=materializeSelected();if(ch){ch.visual.mouthEnabled=e.target.value!=="off";changed()}});on("#toggleMouth","click",()=>{const ch=materializeSelected();if(ch){ch.visual.mouthOpen=!ch.visual.mouthOpen;editPreview={id:ch.id,time};changed()}});on("#hatStyle","change",e=>{const ch=materializeSelected();if(ch){ch.visual.hat=e.target.value;changed()}});on("#hairStyle","change",e=>{const ch=materializeSelected();if(ch){ch.visual.hairStyle=e.target.value;changed()}});on("#characterProp","change",e=>{const ch=materializeSelected();if(ch){ch.prop=e.target.value;changed()}});[["charX","x"],["charY","y"],["charScale","scale"],["charRotation","rotation"]].forEach(([id,key])=>on("#"+id,"change",e=>{const ch=materializeSelected();if(ch){ch[key]=Number(e.target.value);editPreview={id:ch.id,time};changed()}}));on("#flipCharacter","click",()=>{const ch=materializeSelected();if(ch){ch.facing*=-1;changed()}});on("#deleteCharacter","click",()=>{scene.characters=scene.characters.filter(c=>c.id!==selectedId);selectedId=scene.characters[0]?.id||null;changed();syncCharactersUI()});on("#animationClip","change",e=>{const c=MEPModel.ANIMATION_CLIPS[e.target.value];if(c)setVal("#clipDuration",c.duration)});on("#generateClip","click",generateClip);on("#addKeyframe","click",addKeyframe);on("#deleteKeyframe","click",()=>{const ch=selected();if(ch){ch.keyframes=ch.keyframes.filter(k=>Math.abs(k.time-time)>.011);changed()}});

on("#sceneScript","input",e=>{scene.script=e.target.value;project.scripts.sceneById[scene.id]=e.target.value;changed()});on("#sceneCaption","input",e=>{scene.caption=e.target.value;changed()});on("#sceneNotes","input",e=>{scene.notes=e.target.value;changed()});on("#copyUploadInfo","click",()=>navigator.clipboard?.writeText(short.title+"\n\n"+(short.description||"")+"\n\n"+(short.hashtags||[]).join(" ")));on("#copyNarration","click",()=>navigator.clipboard?.writeText(short.scenes.map(s=>s.script).filter(Boolean).join("\n\n")));
on("#addBubble","click",()=>{const style=$("#bubbleStyle").value||"speech",st=MEPModel.BUBBLE_STYLES[style],b={id:MEPModel.id(),text:$("#bubbleText").value||"Dialogue",style,x:170,y:150,width:380,height:120,fontSize:28,fill:st.fill,textColor:st.text,startTime:Number($("#bubbleStart").value)||time,endTime:Number($("#bubbleEnd").value)||Math.min(scene.duration,time+3),tailX:300,tailY:310};scene.bubbles.push(b);selectedBubbleId=b.id;changed();syncBubbles()});on("#deleteBubble","click",()=>{scene.bubbles=scene.bubbles.filter(b=>b.id!==selectedBubbleId);selectedBubbleId=null;changed();syncBubbles()});on("#bubbleText","input",e=>{const b=selectedBubble();if(b){b.text=e.target.value;changed()}});on("#bubbleStyle","change",e=>{const b=selectedBubble();if(b){b.style=e.target.value;changed()}});on("#bubbleStart","change",e=>{const b=selectedBubble();if(b){b.startTime=Number(e.target.value)||0;changed()}});on("#bubbleEnd","change",e=>{const b=selectedBubble();if(b){b.endTime=Math.min(scene.duration,Number(e.target.value)||scene.duration);changed()}});

on("#scrubber","input",e=>{playing=false;editPreview=null;time=Number(e.target.value);render();syncBackgroundUI()});function playTick(now){if(!playing)return;time+=(now-lastFrame)/1000;lastFrame=now;if(time>=scene.duration){time=scene.duration;playing=false}render();if(playing)requestAnimationFrame(playTick)}on("#play","click",()=>{if(time>=scene.duration)time=0;playing=true;lastFrame=performance.now();requestAnimationFrame(playTick)});on("#stop","click",()=>{playing=false;time=0;render()});

let videoPlaying=false,videoTime=0,videoLast=0;
function sceneAtGlobal(sh,t){let off=0;for(let i=0;i<sh.scenes.length;i++){const s=sh.scenes[i];if(t<=off+s.duration||i===sh.scenes.length-1)return{scene:s,index:i,local:Math.max(0,t-off),offset:off};off+=s.duration}return{scene:sh.scenes[0],index:0,local:0,offset:0}}
function renderShortFrame(context,sh,t){const a=sceneAtGlobal(sh,t);renderScene(context,a.scene,a.local,{selectable:false});return a}
function renderVideo(){const a=renderShortFrame(videoCtx,short,videoTime),total=MEPModel.shortDuration(short);setText("#videoCaption",a.scene.caption||"");setText("#videoClock",fmt(videoTime)+" / "+fmt(total));setVal("#videoScrubber",videoTime);$("#videoScrubber").max=total;setText("#videoScript",a.scene.script||"");$("#sceneStrip").innerHTML=short.scenes.map((s,i)=>'<button class="'+(i===a.index?"active":"")+'" data-vscene="'+i+'">'+(i+1)+'. '+esc(s.name)+'</button>').join("");$$("[data-vscene]").forEach(b=>on(b,"click",()=>{videoTime=short.scenes.slice(0,Number(b.dataset.vscene)).reduce((n,s)=>n+s.duration,0);renderVideo()}))}
function videoTick(now){if(!videoPlaying)return;videoTime+=(now-videoLast)/1000;videoLast=now;const total=MEPModel.shortDuration(short);if(videoTime>=total){videoTime=total;videoPlaying=false}renderVideo();if(videoPlaying)requestAnimationFrame(videoTick)}
function setVideoMode(v){document.body.classList.toggle("video-mode",v);$("#editorMode").classList.toggle("active",!v);$("#videoMode").classList.toggle("active",v);if(v){videoTime=0;renderVideo()}}
on("#editorMode","click",()=>setVideoMode(false));on("#videoMode","click",()=>setVideoMode(true));on("#mobileVideo","click",()=>setVideoMode(true));on("#videoPlayPause","click",()=>{videoPlaying=!videoPlaying;if(videoPlaying){if(videoTime>=MEPModel.shortDuration(short))videoTime=0;videoLast=performance.now();requestAnimationFrame(videoTick)}});on("#videoStop","click",()=>{videoPlaying=false;videoTime=0;renderVideo()});on("#videoScrubber","input",e=>{videoPlaying=false;videoTime=Number(e.target.value);renderVideo()});on("#videoPrevScene","click",()=>{const a=sceneAtGlobal(short,videoTime);videoTime=Math.max(0,a.offset-.01);videoTime=sceneAtGlobal(short,videoTime).offset;renderVideo()});on("#videoNextScene","click",()=>{const a=sceneAtGlobal(short,videoTime);videoTime=Math.min(MEPModel.shortDuration(short),a.offset+a.scene.duration+.001);renderVideo()});

async function warmAssets(){await Promise.all((project.assets||[]).filter(a=>a.dataUrl).map(a=>new Promise(resolve=>{const im=imageForAsset(a);if(!im||im.complete)return resolve();im.addEventListener("load",resolve,{once:true});im.addEventListener("error",resolve,{once:true})})))}
async function exportShort(sh,position=1,totalCount=1){
 if(!window.MediaRecorder)return alert("This browser does not support MediaRecorder.");await warmAssets();const c=document.createElement("canvas");c.width=sh.width||720;c.height=sh.height||1280;const x=c.getContext("2d"),stream=c.captureStream(sh.fps||30),mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm",rec=new MediaRecorder(stream,{mimeType:mime}),chunks=[],total=MEPModel.shortDuration(sh);return new Promise((resolve,reject)=>{let timer=null,start=performance.now();rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onerror=e=>{clearInterval(timer);reject(e.error||e)};rec.onstop=()=>{clearInterval(timer);const blob=new Blob(chunks,{type:"video/webm"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(sh.title||"Noveria-History-Short").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"")+".webm";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);resolve()};renderShortFrame(x,sh,0);rec.start(1000);timer=setInterval(()=>{const elapsed=(performance.now()-start)/1000,t=Math.min(total,elapsed);renderShortFrame(x,sh,t);setText("#exportStatus","Rendering "+position+"/"+totalCount+" · "+sh.title+" · "+Math.round(t/total*100)+"%");if(elapsed>=total){clearInterval(timer);setTimeout(()=>rec.stop(),120)}},Math.max(16,1000/(sh.fps||30)))})
}
async function doExportOne(){if(exporting)return;exporting=true;try{await exportShort(short);setText("#exportStatus","Downloaded: "+short.title)}catch(e){alert("Export failed: "+e.message)}finally{exporting=false}}
async function doExportAll(){if(exporting)return;exporting=true;try{for(let i=0;i<project.shorts.length;i++)await exportShort(project.shorts[i],i+1,project.shorts.length);setText("#exportStatus","All "+project.shorts.length+" Shorts exported.")}catch(e){alert("Export stopped: "+e.message)}finally{exporting=false}}
on("#exportCurrentShort","click",doExportOne);on("#previewExport","click",doExportOne);on("#exportAllShorts","click",doExportAll);

let buddyPets=Number(localStorage.getItem("mep-buddy-pets")||0),buddyPetting=false,buddyMoved=false,buddyTimer=null,lastPetAt=0;
function buddyBounds(){const size=58,pad=12,bottom=window.innerWidth<=760?88:18;return{minX:pad,maxX:Math.max(pad,window.innerWidth-size-pad),minY:72,maxY:Math.max(80,window.innerHeight-size-bottom)}}
function moveBuddy(immediate=false){const a=$("#helperAvatar");if(!a)return;if($("#helperPanel").classList.contains("open")){clearTimeout(buddyTimer);buddyTimer=setTimeout(()=>moveBuddy(false),3500);return}const b=buddyBounds(),x=Math.round(b.minX+Math.random()*(b.maxX-b.minX)),y=Math.round(b.minY+Math.random()*(b.maxY-b.minY));a.style.left=x+"px";a.style.top=y+"px";a.style.right="auto";a.style.bottom="auto";a.style.transition=immediate?"none":"left 2.8s ease-in-out, top 2.8s ease-in-out, transform .2s ease";clearTimeout(buddyTimer);buddyTimer=setTimeout(()=>moveBuddy(false),4500+Math.random()*4500)}
function positionBuddyPanel(){const a=$("#helperAvatar"),p=$("#helperPanel");if(!a||!p)return;const r=a.getBoundingClientRect(),w=Math.min(330,window.innerWidth-24),left=Math.max(12,Math.min(window.innerWidth-w-12,r.left+r.width/2-w/2)),above=r.top>360;p.style.width=w+"px";p.style.left=left+"px";p.style.right="auto";p.style.top=above?Math.max(12,r.top-330)+"px":Math.min(window.innerHeight-350,r.bottom+10)+"px";p.style.bottom="auto"}
function petBuddy(){const now=Date.now();if(now-lastPetAt<260)return;lastPetAt=now;buddyPets++;localStorage.setItem("mep-buddy-pets",buddyPets);setText("#petCount","Pets: "+buddyPets);setText("#helperFace",buddyPets%5===0?"^▽^":"•ᴗ•");const a=$("#helperAvatar"),h=$("#petHeart");a.classList.remove("petted");void a.offsetWidth;a.classList.add("petted");h.classList.remove("show");void h.offsetWidth;h.classList.add("show");setTimeout(()=>setText("#helperFace","•‿•"),1000)}
on("#helperAvatar","click",()=>{if(buddyMoved){buddyMoved=false;return}$("#helperPanel").classList.toggle("open");positionBuddyPanel()});on("#helperAvatar","pointerenter",e=>{if(e.pointerType==="mouse")petBuddy()});on("#helperAvatar","pointerdown",e=>{buddyPetting=true;buddyMoved=false;$("#helperAvatar").setPointerCapture?.(e.pointerId)});on("#helperAvatar","pointermove",()=>{if(buddyPetting){buddyMoved=true;petBuddy()}});on("#helperAvatar","pointerup",()=>buddyPetting=false);on("#closeHelper","click",()=>$("#helperPanel").classList.remove("open"));$$("[data-jump]").forEach(b=>on(b,"click",()=>{document.querySelector(b.dataset.jump)?.scrollIntoView({behavior:"smooth",block:"start"});$("#helperPanel").classList.remove("open")}));on("#helperLoadPack","click",()=>loadShortPack().then(()=>$("#helperPanel").classList.remove("open")));on("#helperExport","click",()=>{doExportOne();$("#helperPanel").classList.remove("open")});on("#helperVideoMode","click",()=>{setVideoMode(true);$("#helperPanel").classList.remove("open")});on("#helperOpenAI","click",()=>$("#aiDialog").showModal());setText("#petCount","Pets: "+buddyPets);setTimeout(()=>moveBuddy(true),700);

on("#aiShowContext","click",()=>$("#aiJson").value=JSON.stringify(MEPAIDirector.promptPackage($("#aiPrompt").value,project),null,2));on("#aiGenerate","click",async()=>{try{setText("#aiStatus","Generating…");const plan=await MEPAIDirector.generate($("#aiPrompt").value.trim(),project);$("#aiJson").value=JSON.stringify(plan,null,2);setText("#aiStatus","Plan ready")}catch(e){setText("#aiStatus",e.message)}});on("#aiApply","click",()=>{try{project=MEPModel.migrate(MEPAIDirector.apply(JSON.parse($("#aiJson").value)));refreshRefs();changed();syncUI();$("#aiDialog").close()}catch(e){setText("#aiStatus",e.message)}});

try{syncUI()}catch(e){console.error(e);$("#bootStatus").className="bootStatus error";setText("#bootStatus","Startup error: "+e.message)}
MEPStorage.initCloud().then(async r=>{if(!r.ok){setText("#saveStatus","Local autosave");return}try{await MEPStorage.seedLibrary(MEPModel.librarySnapshot());cloudReady=true;setText("#saveStatus","Firestore ready");syncBuddy()}catch(e){console.warn(e);setText("#saveStatus","Local autosave")}});

window.MEP_DEBUG={get project(){return project},get short(){return short},get scene(){return scene},render,syncUI,exportShort};
})();
if(window.speechSynthesis){speechSynthesis.addEventListener?.("voiceschanged",()=>{try{populateChromeVoices()}catch{}})}
