(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const on=(s,e,fn)=>{const el=typeof s==="string"?$(s):s;if(el)el.addEventListener(e,fn);return el};
const canvas=$("#stage"),ctx=canvas?.getContext("2d");if(!canvas||!ctx)return;
ctx.fillStyle="#dbe5d2";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#172019";ctx.font="700 44px system-ui";ctx.fillText("MEP Video Maker",54,84);ctx.font="24px system-ui";ctx.fillText("Loading the editor…",54,128);

const imageCache=new Map();let cloudReady=false,cloudTimer=null,project,scene,selectedId=null,selectedBubbleId=null,time=0,playing=false,lastFrame=0,drag=null,editPreview=null;
const hadLocal=MEPStorage.hasLocal?.()||false;
try{project=MEPModel.migrate(MEPStorage.load()||MEPModel.project())}catch(e){console.warn(e);project=MEPModel.project()}
scene=MEPModel.activeScene(project);selectedId=scene?.characters?.[0]?.id||null;

const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const selected=()=>scene?.characters?.find(c=>c.id===selectedId)||null;
const selectedBubble=()=>scene?.bubbles?.find(b=>b.id===selectedBubbleId)||null;
const assetById=id=>(project.assets||[]).find(a=>a.id===id)||null;
const visibleBubbles=(s,t)=>(s.bubbles||[]).filter(b=>t>=(b.startTime??0)&&t<=(b.endTime??s.duration));
const sceneIndex=()=>Math.max(0,project.scenes.findIndex(s=>s.id===scene.id));
const setText=(id,v)=>{const el=$(id);if(el)el.textContent=v};
const setVal=(id,v)=>{const el=$(id);if(el&&document.activeElement!==el)el.value=v??""};
const fmt=t=>{const m=Math.floor(t/60),s=Math.floor(t%60);return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")};

function imageForAsset(asset){
 if(!asset?.dataUrl)return null;if(imageCache.has(asset.id))return imageCache.get(asset.id);const im=new Image();im.src=asset.dataUrl;imageCache.set(asset.id,im);im.onload=()=>{render();if(document.body.classList.contains("video-mode"))renderVideo()};return im
}
function drawImageFit(context,img,bg={}){
 if(!img?.complete)return;const cw=context.canvas.width,ch=context.canvas.height,iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height;if(!iw||!ih)return;const fit=bg.fit||"cover",opacity=bg.opacity??1,userScale=Math.max(.25,Number(bg.scale)||1),panX=Number(bg.panX)||0,panY=Number(bg.panY)||0,brightness=Math.max(.2,Number(bg.brightness)||1),blur=Math.max(0,Number(bg.blur)||0);context.save();context.globalAlpha=Math.max(0,Math.min(1,opacity));context.filter="brightness("+brightness+") blur("+blur+"px)";
 if(fit==="stretch"){const w=cw*userScale,h=ch*userScale;context.drawImage(img,(cw-w)/2+panX,(ch-h)/2+panY,w,h)}else{const base=fit==="contain"?Math.min(cw/iw,ch/ih):Math.max(cw/iw,ch/ih),scale=base*userScale,w=iw*scale,h=ih*scale;context.drawImage(img,(cw-w)/2+panX,(ch-h)/2+panY,w,h)}context.restore()
}
function renderBackground(context,s,t){
 const bg=MEPModel.backgroundAt(s,t);MEPRenderer.drawBackground(context,bg.preset||"countryside",context.canvas.width,context.canvas.height);
 if(bg.mode==="image"&&bg.assetId){const a=assetById(bg.assetId),im=imageForAsset(a);if(im)drawImageFit(context,im,bg)}
 return bg
}
function stateFor(ch){if(!playing&&editPreview?.id===ch.id&&Math.abs(editPreview.time-time)<.001)return MEPModel.capture(ch);return(time>0||playing)?MEPModel.poseAt(ch,time):MEPModel.capture(ch)}
function renderScene(context,s,t,{selectable=false}={}){
 const cam=s.camera||{x:640,y:360,zoom:1};context.save();context.clearRect(0,0,context.canvas.width,context.canvas.height);context.translate(context.canvas.width/2,context.canvas.height/2);context.scale(cam.zoom||1,cam.zoom||1);context.translate(-(cam.x??640),-(cam.y??360));renderBackground(context,s,t);
 [...(s.characters||[])].sort((a,b)=>(a.layer||0)-(b.layer||0)).forEach(ch=>{const st=selectable&&s.id===scene.id?stateFor(ch):MEPModel.poseAt(ch,t);MEPRenderer.drawCharacter(context,st,ch,selectable&&ch.id===selectedId)});context.restore();
 visibleBubbles(s,t).forEach(b=>MEPRenderer.drawBubble(context,b))
}
function render(){renderScene(ctx,scene,time,{selectable:true});setText("#timeLabel",time.toFixed(2)+" / "+scene.duration.toFixed(2)+"s");setVal("#scrubber",time)}
function changed({cloud=true}={}){
 project.updatedAt=new Date().toISOString();MEPStorage.save(project);setText("#saveStatus",cloudReady?"Saving…":"Local ✓");drawTimeline();render();syncHelper();
 if(cloud&&cloudReady){clearTimeout(cloudTimer);cloudTimer=setTimeout(async()=>{try{await MEPStorage.saveCloud(project);setText("#saveStatus","Firestore ✓")}catch(e){console.warn(e);setText("#saveStatus","Local ✓")}},1800)}
}
function materializeSelected(){const ch=selected();if(!ch)return null;if(time>0&&!(editPreview?.id===ch.id&&Math.abs(editPreview.time-time)<.001)){const st=MEPModel.stateAt(ch,time);ch.x=st.x;ch.y=st.y;ch.scale=st.scale;ch.rotation=st.rotation||0;ch.facing=st.facing;ch.visual.mouthOpen=!!st.mouthOpen;editPreview={id:ch.id,time}}return ch}
function setYear(year){
 year=Math.max(1600,Math.min(2026,Math.round(Number(year)||1863)));project.year=year;project.era=MEPModel.yearToEra(year);
 for(const s of project.scenes)for(const ch of s.characters||[])if(ch.visual?.followProjectYear!==false)ch.visual.historicalYear=year;
 changed();syncUI()
}
function setScene(s){scene=s;project.activeSceneId=s.id;selectedId=s.characters?.[0]?.id||null;selectedBubbleId=null;time=0;playing=false;editPreview=null;syncUI()}
function selectSceneByIndex(i){i=Math.max(0,Math.min(project.scenes.length-1,i));setScene(project.scenes[i]);changed()}
function cloneScene(src){const s=structuredClone(src);s.id=MEPModel.id();s.name=src.name+" Copy";s.characters=(s.characters||[]).map(ch=>({...ch,id:MEPModel.id(),keyframes:(ch.keyframes||[]).map(k=>({...k,id:MEPModel.id()}))}));s.bubbles=(s.bubbles||[]).map(b=>({...b,id:MEPModel.id()}));s.background.keyframes=(s.background.keyframes||[]).map(k=>({...k,id:MEPModel.id()}));return s}

function syncSceneUI(){
 $("#sceneSelect").innerHTML=project.scenes.map(s=>'<option value="'+s.id+'">'+esc(s.name)+'</option>').join("");setVal("#sceneSelect",scene.id);
 $("#sceneBoard").innerHTML=project.scenes.map((s,i)=>'<button class="sceneCard '+(s.id===scene.id?"active":"")+'" data-scene="'+s.id+'"><strong>'+(i+1)+'. '+esc(s.name)+'</strong><small>'+s.duration.toFixed(1)+'s · '+(s.characters?.length||0)+' chars · '+esc(s.transition?.type||"cut")+'</small></button>').join("");
 $$("[data-scene]").forEach(b=>on(b,"click",()=>{const s=project.scenes.find(x=>x.id===b.dataset.scene);if(s)setScene(s)}));
 setVal("#sceneTransition",scene.transition?.type||"cut");setVal("#duration",scene.duration);setVal("#fps",project.fps);setVal("#cameraX",scene.camera?.x??640);setVal("#cameraY",scene.camera?.y??360);setVal("#cameraZoom",scene.camera?.zoom??1)
}
function syncBackgroundUI(){
 const keys=Object.keys(MEPModel.BACKGROUNDS);$("#backgroundPreset").innerHTML=keys.map(k=>'<option value="'+k+'">'+esc(MEPModel.BACKGROUNDS[k].name)+'</option>').join("");const bg=MEPModel.backgroundAt(scene,time);setVal("#backgroundPreset",bg.preset||scene.background.preset);setVal("#backgroundFit",bg.fit||"cover");setVal("#backgroundOpacity",bg.opacity??1);setVal("#backgroundPanX",bg.panX||0);setVal("#backgroundPanY",bg.panY||0);setVal("#backgroundScale",bg.scale||1);setVal("#backgroundBrightness",bg.brightness??1);setVal("#backgroundBlur",bg.blur||0);
 setText("#backgroundModeLabel",bg.mode==="image"?"Image background":"Drawn background");const a=assetById(bg.assetId);setText("#backgroundAssetLabel",a?a.name:"");
 $("#backgroundKeyframes").innerHTML=(scene.background.keyframes||[]).map((k,i)=>'<div class="characterItem"><button data-bg-time="'+k.time+'">'+k.time.toFixed(2)+'s · '+esc(k.mode||"preset")+'</button><button data-bg-del="'+i+'" class="danger">Delete</button></div>').join("");
 $$("[data-bg-time]").forEach(b=>on(b,"click",()=>{time=Number(b.dataset.bgTime);editPreview=null;render();syncBackgroundUI()}));$$("[data-bg-del]").forEach(b=>on(b,"click",()=>{scene.background.keyframes.splice(Number(b.dataset.bgDel),1);changed();syncBackgroundUI()}))
}
function fillLookOptions(){
 $("#characterShape").innerHTML=Object.entries(MEPModel.SHAPES).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join("");
 $("#expression").innerHTML=MEPModel.EXPRESSIONS.map(x=>'<option value="'+x+'">'+x[0].toUpperCase()+x.slice(1)+'</option>').join("");
 $("#characterProp").innerHTML=Object.entries(MEPModel.PROPS).map(([k,v])=>'<option value="'+k+'">'+v.name+'</option>').join("");
 $("#animationClip").innerHTML=Object.entries(MEPModel.ANIMATION_CLIPS).map(([k,v])=>'<option value="'+k+'">'+v.name+'</option>').join("");
 $("#keyframeEasing").innerHTML=Object.entries(MEPModel.EASINGS).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join("")
}
function syncCharactersUI(){
 const eraKeys=MEPModel.ERA_CHARACTER_PRESETS[project.era]||Object.keys(MEPModel.CHARACTER_PRESETS);$("#characterPreset").innerHTML=eraKeys.filter(k=>MEPModel.CHARACTER_PRESETS[k]).map(k=>'<option value="'+k+'">'+esc(MEPModel.CHARACTER_PRESETS[k].name)+'</option>').join("");
 const quick=["unionSquare","american1776","britishEmpire","haitiRevolution","confederateHistorical","modernGB"];$("#quickPresetGrid").innerHTML=quick.filter(k=>MEPModel.CHARACTER_PRESETS[k]).map(k=>'<button data-quick="'+k+'">'+esc(MEPModel.CHARACTER_PRESETS[k].name)+'</button>').join("");$$("[data-quick]").forEach(b=>on(b,"click",()=>addPreset(b.dataset.quick)));
 $("#characterList").innerHTML=(scene.characters||[]).map(ch=>{const flag=MEPHistoryFlags.resolve(ch.visual?.countryCode||"US",ch.visual?.historicalYear||project.year,ch.visual?.flagVariant||"auto");return'<button class="characterItem '+(ch.id===selectedId?"active":"")+'" data-char="'+ch.id+'"><strong>'+esc(ch.name)+'</strong><small>'+esc(ch.visual?.shape||"square")+' · '+esc(flag.label)+'</small></button>'}).join("");$$("[data-char]").forEach(b=>on(b,"click",()=>{selectedId=b.dataset.char;editPreview=null;syncUI()}));
 const ch=selected();if(!ch)return;setVal("#charName",ch.name);setVal("#characterShape",ch.visual?.shape||"square");setVal("#expression",ch.visual?.expression||"neutral");setVal("#mouthMode",ch.visual?.mouthEnabled===false?"off":"on");setVal("#hatStyle",ch.visual?.hat||"none");setVal("#hairStyle",ch.visual?.hairStyle||"none");setVal("#characterProp",ch.prop||"none");setVal("#charX",Math.round(ch.x));setVal("#charY",Math.round(ch.y));setVal("#charScale",ch.scale);setVal("#charRotation",ch.rotation||0);
 const opts=MEPHistoryFlags.options(project.year);$("#countryCode").innerHTML=opts.map(o=>'<option value="'+o.code+'">'+(o.historical?"★ ":"")+esc(o.name)+'</option>').join("");setVal("#countryCode",ch.visual?.countryCode||"US");const flag=MEPHistoryFlags.resolve(ch.visual?.countryCode||"US",project.year,ch.visual?.flagVariant||"auto");setText("#flagLabel",flag.label+" · "+project.year)
}
function syncScripts(){setVal("#projectScript",project.scripts?.project||"");setVal("#sceneScript",scene.script||project.scripts?.sceneById?.[scene.id]||"");setVal("#sceneCaption",scene.caption||"");setVal("#sceneNotes",scene.notes||"")}
function syncBubbles(){
 $("#bubbleStyle").innerHTML=Object.entries(MEPModel.BUBBLE_STYLES).map(([k,v])=>'<option value="'+k+'">'+v.name+'</option>').join("");$("#bubbleList").innerHTML=(scene.bubbles||[]).map(b=>'<button class="bubbleItem '+(b.id===selectedBubbleId?"active":"")+'" data-bubble="'+b.id+'">'+esc(b.text||"Bubble")+'</button>').join("");$$("[data-bubble]").forEach(b=>on(b,"click",()=>{selectedBubbleId=b.dataset.bubble;syncBubbles()}));
 const b=selectedBubble();if(b){setVal("#bubbleText",b.text||"");setVal("#bubbleStyle",b.style||"speech");setVal("#bubbleStart",b.startTime??0);setVal("#bubbleEnd",b.endTime??scene.duration)}else{setVal("#bubbleText","");setVal("#bubbleStart",time);setVal("#bubbleEnd",Math.min(scene.duration,time+3))}
}
function syncHelper(){const ch=selected();setText("#helperYear",project.year+" · "+project.era);setText("#helperScene",scene.name);setText("#helperCharacter",ch?.name||"No character");setText("#helperStatus",cloudReady?"Firestore synced":"Local mode")}
function syncUI(){
 fillLookOptions();setVal("#projectName",project.name);setVal("#projectYear",project.year);setVal("#yearSlider",project.year);setText("#eraBadge",project.era);syncSceneUI();syncBackgroundUI();syncCharactersUI();syncScripts();syncBubbles();$("#scrubber").max=scene.duration;setVal("#scrubber",Math.min(time,scene.duration));drawTimeline();render();syncHelper();
 setText("#bootStatus","MEP ready · "+Object.keys(MEPModel.CHARACTER_PRESETS).length+" presets · "+Object.keys(MEPModel.BACKGROUNDS).length+" backgrounds");$("#bootStatus").className="bootStatus ready"
}
function drawTimeline(){
 const dur=Math.max(.01,scene.duration),markers='<div class="track"><div class="trackName">Markers</div><div class="trackLane">'+(scene.markers||[]).map(m=>'<span class="markerKey" data-marker="'+m.time+'" style="left:'+(m.time/dur*100)+'%" title="'+esc(m.label||"Marker")+'"></span>').join("")+'</div></div>',bg='<div class="track"><div class="trackName">Background</div><div class="trackLane">'+(scene.background.keyframes||[]).map(k=>'<span class="bgKey" data-bgt="'+k.time+'" style="left:'+(k.time/dur*100)+'%" title="Background '+k.time.toFixed(2)+'s"></span>').join("")+'</div></div>',bubbles='<div class="track"><div class="trackName">Dialogue</div><div class="trackLane">'+(scene.bubbles||[]).map(b=>{const a=b.startTime??0,z=b.endTime??dur;return'<span class="bubbleRange" data-bid="'+b.id+'" style="left:'+(a/dur*100)+'%;width:'+Math.max(.6,(z-a)/dur*100)+'%"></span>'}).join("")+'</div></div>',chars=(scene.characters||[]).map(ch=>'<div class="track"><div class="trackName">'+esc(ch.name)+'</div><div class="trackLane">'+(ch.keyframes||[]).map(k=>'<span class="key" data-kchar="'+ch.id+'" data-ktime="'+k.time+'" style="left:'+(k.time/dur*100)+'%" title="'+k.time.toFixed(2)+'s · '+esc(k.easing||"linear")+'"></span>').join("")+'</div></div>').join("");
 $("#timeline").innerHTML=markers+bg+bubbles+chars;$$("[data-marker]").forEach(x=>on(x,"click",()=>{time=Number(x.dataset.marker);editPreview=null;render()}));$$("[data-bgt]").forEach(x=>on(x,"click",()=>{time=Number(x.dataset.bgt);editPreview=null;render();syncBackgroundUI()}));$$("[data-bid]").forEach(x=>on(x,"click",()=>{selectedBubbleId=x.dataset.bid;const b=selectedBubble();time=b?.startTime??time;syncBubbles();render()}));$$("[data-kchar]").forEach(x=>on(x,"click",()=>{selectedId=x.dataset.kchar;time=Number(x.dataset.ktime);editPreview=null;syncUI()}))
}
function addPreset(key){
 const p=MEPModel.CHARACTER_PRESETS[key]||MEPModel.CHARACTER_PRESETS.unionSquare,ch=MEPModel.character(p.name,380+(scene.characters.length%4)*180,430,key);ch.visual.historicalYear=project.year;scene.characters.push(ch);selectedId=ch.id;editPreview=null;changed();syncUI()
}
function addKeyframe(){
 const ch=materializeSelected();if(!ch)return;const q=Math.max(0,Math.min(scene.duration,Math.round(time*100)/100)),state=MEPModel.capture(ch),ease=$("#keyframeEasing")?.value||"linear",old=ch.keyframes.find(k=>Math.abs(k.time-q)<.011);if(old){old.state=state;old.easing=ease}else ch.keyframes.push({id:MEPModel.id(),time:q,easing:ease,state});ch.keyframes.sort((a,b)=>a.time-b.time);editPreview=null;changed()
}
function generateClip(){
 const ch=materializeSelected();if(!ch)return;const key=$("#animationClip").value,clip=MEPModel.ANIMATION_CLIPS[key];if(!clip)return;const duration=Math.max(.5,Number($("#clipDuration").value)||clip.duration),start=time,steps=Math.max(2,clip.scale?.length||0,clip.rotation?.length||0,clip.mouth?.length||0,clip.y?.length||0),dt=duration/(steps-1),base={x:ch.x,y:ch.y,scale:ch.scale,rotation:ch.rotation||0,facing:ch.facing,mouthOpen:!!ch.visual.mouthOpen};scene.duration=Math.max(scene.duration,start+duration);
 for(let i=0;i<steps;i++){const t=start+i*dt,ratio=i/(steps-1),pick=(arr,def)=>arr?.[Math.min(i,arr.length-1)]??def;ch.x=base.x+(clip.move||0)*ratio*base.facing;ch.y=base.y+pick(clip.y,0);ch.scale=base.scale*pick(clip.scale,1);ch.rotation=base.rotation+pick(clip.rotation,0);ch.visual.mouthOpen=!!pick(clip.mouth,false);const state=MEPModel.capture(ch),old=ch.keyframes.find(k=>Math.abs(k.time-t)<.011),kf={id:MEPModel.id(),time:Math.round(t*100)/100,easing:i?"easeInOut":"linear",state};if(old)Object.assign(old,kf);else ch.keyframes.push(kf)}
 ch.x=base.x;ch.y=base.y;ch.scale=base.scale;ch.rotation=base.rotation;ch.facing=base.facing;ch.visual.mouthOpen=base.mouthOpen;ch.keyframes.sort((a,b)=>a.time-b.time);editPreview=null;changed();syncUI()
}
async function compressImage(file){
 const bitmap=await createImageBitmap(file),maxW=1600,maxH=900,scale=Math.min(1,maxW/bitmap.width,maxH/bitmap.height),c=document.createElement("canvas");c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));c.getContext("2d").drawImage(bitmap,0,0,c.width,c.height);let q=.82,url=c.toDataURL("image/jpeg",q);while(url.length>780000&&q>.38){q-=.08;url=c.toDataURL("image/jpeg",q)}return{id:MEPModel.id(),name:file.name.replace(/.[^.]+$/,"")+".jpg",type:"image/jpeg",size:url.length,dataUrl:url}
}
function worldPos(p){const cam=scene.camera||{x:640,y:360,zoom:1},z=cam.zoom||1;return{x:(p.x-canvas.width/2)/z+(cam.x??640),y:(p.y-canvas.height/2)/z+(cam.y??360)}}
function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}

on(canvas,"pointerdown",e=>{
 const p=pointerPos(e),bubble=[...visibleBubbles(scene,time)].reverse().find(b=>p.x>=b.x&&p.x<=b.x+(b.width||300)&&p.y>=b.y&&p.y<=b.y+(b.height||100));if(bubble){selectedBubbleId=bubble.id;drag={type:"bubble",dx:p.x-bubble.x,dy:p.y-bubble.y};canvas.setPointerCapture(e.pointerId);syncBubbles();return}
 const wp=worldPos(p);let best=null,bestArea=Infinity;for(const ch of scene.characters||[]){const st=stateFor(ch),b=MEPRenderer.bounds(st,ch);if(wp.x>=b.x&&wp.x<=b.x+b.w&&wp.y>=b.y&&wp.y<=b.y+b.h&&b.w*b.h<bestArea){best=ch;bestArea=b.w*b.h}}if(best){selectedId=best.id;const ch=materializeSelected();drag={type:"char",dx:wp.x-ch.x,dy:wp.y-ch.y};canvas.setPointerCapture(e.pointerId);syncCharactersUI()}
});
on(canvas,"pointermove",e=>{if(!drag)return;const p=pointerPos(e);if(drag.type==="bubble"){const b=selectedBubble();if(b){b.x=Math.max(0,Math.min(canvas.width-(b.width||300),p.x-drag.dx));b.y=Math.max(0,Math.min(canvas.height-(b.height||100),p.y-drag.dy));render()}return}const ch=selected(),wp=worldPos(p);if(ch){ch.x=wp.x-drag.dx;ch.y=wp.y-drag.dy;editPreview={id:ch.id,time};render()}});
on(canvas,"pointerup",()=>{if(drag){drag=null;changed();syncCharactersUI()}});

on("#projectName","input",e=>{project.name=e.target.value;changed()});on("#projectYear","change",e=>setYear(e.target.value));on("#yearSlider","input",e=>{setVal("#projectYear",e.target.value);setYear(e.target.value)});
on("#quickStart","click",()=>{project=MEPModel.project();scene=MEPModel.activeScene(project);selectedId=scene.characters[0].id;selectedBubbleId=null;time=0;changed();syncUI()});
async function loadPresetFile(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw new Error("Could not load preset");project=MEPModel.migrate(await r.json());scene=MEPModel.activeScene(project);selectedId=scene.characters[0]?.id||null;selectedBubbleId=null;time=0;changed({cloud:false});syncUI()}
on("#loadStarterPack","click",()=>loadPresetFile("presets/mep-starter-pack-v6.mep.json").catch(e=>alert(e.message)));on("#loadHaitiDemo","click",()=>loadPresetFile("presets/haiti-vertieres-30s.mep.json").catch(e=>alert(e.message)));
on("#saveProject","click",()=>{MEPStorage.save(project);setText("#saveStatus","Local ✓")});on("#saveCloud","click",async()=>{try{setText("#saveStatus","Saving…");await MEPStorage.saveCloud(project);setText("#saveStatus","Firestore ✓")}catch(e){alert(e.message);setText("#saveStatus","Cloud blocked")}});
on("#loadCloud","click",async()=>{try{const items=await MEPStorage.listCloud();$("#cloudProjectList").innerHTML=items.length?items.map(x=>'<button class="cloudCard" data-cloud="'+x.id+'"><strong>'+esc(x.name)+'</strong><small>'+esc(String(x.year||""))+' · '+x.sceneCount+' scenes</small></button>').join(""):'<p>No Firestore projects yet.</p>';$$("[data-cloud]").forEach(b=>on(b,"click",async()=>{project=await MEPStorage.loadCloud(b.dataset.cloud);scene=MEPModel.activeScene(project);selectedId=scene.characters[0]?.id||null;time=0;$("#cloudDialog").close();syncUI()}));$("#cloudDialog").showModal()}catch(e){alert(e.message)}});
on("#closeCloudDialog","click",()=>$("#cloudDialog").close());on("#exportProject","click",()=>MEPStorage.download(project));on("#importProject","change",async e=>{const f=e.target.files?.[0];if(!f)return;try{const p=MEPModel.migrate(JSON.parse(await f.text())),v=MEPModel.validateProject(p);if(!v.ok)throw new Error(v.errors.join("; "));project=p;scene=MEPModel.activeScene(project);selectedId=scene.characters[0]?.id||null;time=0;changed({cloud:false});syncUI()}catch(err){alert("Import failed: "+err.message)}e.target.value=""});

on("#sceneSelect","change",e=>{const s=project.scenes.find(x=>x.id===e.target.value);if(s)setScene(s)});on("#prevScene","click",()=>selectSceneByIndex(sceneIndex()-1));on("#nextScene","click",()=>selectSceneByIndex(sceneIndex()+1));on("#addScene","click",()=>{const s=MEPModel.scene("Scene "+(project.scenes.length+1));project.scenes.push(s);setScene(s);changed()});on("#duplicateScene","click",()=>{const i=sceneIndex(),s=cloneScene(scene);project.scenes.splice(i+1,0,s);setScene(s);changed()});on("#deleteScene","click",()=>{if(project.scenes.length<=1)return alert("A project needs at least one scene.");if(!confirm("Delete this scene?"))return;const i=sceneIndex();project.scenes.splice(i,1);setScene(project.scenes[Math.min(i,project.scenes.length-1)]);changed()});
on("#sceneTransition","change",e=>{scene.transition.type=e.target.value;changed()});on("#duration","change",e=>{scene.duration=Math.max(1,Number(e.target.value)||8);time=Math.min(time,scene.duration);changed();syncUI()});on("#fps","change",e=>{project.fps=Number(e.target.value)||30;changed()});
["cameraX","cameraY","cameraZoom"].forEach(id=>on("#"+id,"change",()=>{scene.camera.x=Number($("#cameraX").value)||640;scene.camera.y=Number($("#cameraY").value)||360;scene.camera.zoom=Math.max(.5,Math.min(3,Number($("#cameraZoom").value)||1));changed()}));

on("#backgroundPreset","change",e=>{scene.background.preset=e.target.value;if(scene.background.mode!=="image")scene.background.mode="preset";changed();syncBackgroundUI()});
function cycleSelect(id,d){const el=$(id);if(!el?.options.length)return;el.selectedIndex=(el.selectedIndex+d+el.options.length)%el.options.length;el.dispatchEvent(new Event("change"))}
on("#prevBackground","click",()=>cycleSelect("#backgroundPreset",-1));on("#nextBackground","click",()=>cycleSelect("#backgroundPreset",1));on("#useDrawnBackground","click",()=>{scene.background.mode="preset";scene.background.assetId=null;changed();syncBackgroundUI()});on("#backgroundFit","change",e=>{scene.background.fit=e.target.value;changed()});[["backgroundPanX","panX"],["backgroundPanY","panY"],["backgroundScale","scale"],["backgroundOpacity","opacity"],["backgroundBrightness","brightness"],["backgroundBlur","blur"]].forEach(([id,key])=>on("#"+id,"change",e=>{scene.background[key]=Number(e.target.value);changed();syncBackgroundUI()}));
on("#backgroundUpload","change",async e=>{const f=e.target.files?.[0];if(!f)return;try{setText("#backgroundAssetLabel","Compressing…");const a=await compressImage(f);project.assets=project.assets||[];project.assets.push(a);scene.background.mode="image";scene.background.assetId=a.id;scene.background.fit="cover";scene.background.opacity=1;changed();syncBackgroundUI()}catch(err){alert("Image import failed: "+err.message)}e.target.value=""});
function addBackgroundKey(){const bg=MEPModel.backgroundAt(scene,time),kf={id:MEPModel.id(),time:Math.round(time*100)/100,preset:bg.preset,mode:bg.mode,assetId:bg.assetId||null,fit:bg.fit||"cover",opacity:bg.opacity??1,panX:bg.panX||0,panY:bg.panY||0,scale:bg.scale||1,brightness:bg.brightness??1,blur:bg.blur||0};const old=scene.background.keyframes.find(k=>Math.abs(k.time-kf.time)<.011);if(old)Object.assign(old,kf);else scene.background.keyframes.push(kf);scene.background.keyframes.sort((a,b)=>a.time-b.time);changed();syncBackgroundUI()}
on("#addBackgroundKeyframe","click",addBackgroundKey);

on("#addCharacter","click",()=>addPreset("unionSquare"));on("#addPresetCharacter","click",()=>addPreset($("#characterPreset").value));on("#openCharacterGallery","click",()=>{const entries=Object.entries(MEPModel.CHARACTER_PRESETS).sort((a,b)=>(a[1].era+" "+a[1].name).localeCompare(b[1].era+" "+b[1].name));$("#characterGalleryList").innerHTML=entries.map(([k,p])=>'<button class="characterCard" data-gallery="'+k+'"><strong>'+esc(p.name)+'</strong><span>'+esc(p.era)+'</span><small>'+esc(p.shape||"square")+' · '+esc(MEPHistoryFlags.resolve(p.countryCode||"US",p.year||project.year).label)+'</small></button>').join("");$$("[data-gallery]").forEach(b=>on(b,"click",()=>{addPreset(b.dataset.gallery);$("#characterGalleryDialog").close()}));$("#characterGalleryDialog").showModal()});on("#closeCharacterGallery","click",()=>$("#characterGalleryDialog").close());
on("#charName","input",e=>{const ch=selected();if(ch){ch.name=e.target.value;changed()}});on("#characterShape","change",e=>{const ch=materializeSelected();if(ch){ch.visual.shape=e.target.value;changed();syncCharactersUI()}});on("#countryCode","change",e=>{const ch=materializeSelected();if(ch){ch.visual.countryCode=e.target.value;ch.visual.historicalYear=project.year;ch.visual.flagVariant="auto";changed();syncCharactersUI()}});
on("#expression","change",e=>{const ch=materializeSelected();if(ch){ch.visual.expression=e.target.value;changed()}});on("#mouthMode","change",e=>{const ch=materializeSelected();if(ch){ch.visual.mouthEnabled=e.target.value!=="off";changed()}});on("#toggleMouth","click",()=>{const ch=materializeSelected();if(ch){ch.visual.mouthOpen=!ch.visual.mouthOpen;editPreview={id:ch.id,time};changed()}});
on("#hatStyle","change",e=>{const ch=materializeSelected();if(ch){ch.visual.hat=e.target.value;changed()}});on("#hairStyle","change",e=>{const ch=materializeSelected();if(ch){ch.visual.hairStyle=e.target.value;changed()}});on("#characterProp","change",e=>{const ch=materializeSelected();if(ch){ch.prop=e.target.value;changed()}});
[["charX","x"],["charY","y"],["charScale","scale"],["charRotation","rotation"]].forEach(([id,key])=>on("#"+id,"change",e=>{const ch=materializeSelected();if(ch){ch[key]=Number(e.target.value);editPreview={id:ch.id,time};changed()}}));on("#flipCharacter","click",()=>{const ch=materializeSelected();if(ch){ch.facing*=-1;changed()}});on("#deleteCharacter","click",()=>{if(!selectedId)return;scene.characters=scene.characters.filter(c=>c.id!==selectedId);selectedId=scene.characters[0]?.id||null;editPreview=null;changed();syncUI()});

on("#animationClip","change",e=>{const c=MEPModel.ANIMATION_CLIPS[e.target.value];if(c)setVal("#clipDuration",c.duration)});on("#generateClip","click",generateClip);on("#addKeyframe","click",addKeyframe);on("#deleteKeyframe","click",()=>{const ch=selected();if(!ch)return;ch.keyframes=ch.keyframes.filter(k=>Math.abs(k.time-time)>.011);changed()});on("#saveCharacterCloud","click",async()=>{const ch=selected();if(!ch)return;try{await MEPStorage.saveCharacter(ch);setText("#saveStatus","Character saved")}catch(e){alert(e.message)}});

on("#projectScript","input",e=>{project.scripts.project=e.target.value;changed()});on("#sceneScript","input",e=>{scene.script=e.target.value;project.scripts.sceneById[scene.id]=e.target.value;changed()});on("#sceneCaption","input",e=>{scene.caption=e.target.value;changed()});on("#sceneNotes","input",e=>{scene.notes=e.target.value;changed()});on("#copySceneScript","click",()=>navigator.clipboard?.writeText(scene.script||""));on("#copyProjectScript","click",()=>navigator.clipboard?.writeText(project.scripts.project||""));
on("#addBubble","click",()=>{const st=MEPModel.BUBBLE_STYLES[$("#bubbleStyle").value]||MEPModel.BUBBLE_STYLES.speech,b={id:MEPModel.id(),type:"bubble",text:$("#bubbleText").value||"Dialogue",style:$("#bubbleStyle").value||"speech",x:360,y:90,width:340,height:100,fontSize:28,fill:st.fill,textColor:st.text,startTime:Number($("#bubbleStart").value)||time,endTime:Number($("#bubbleEnd").value)||Math.min(scene.duration,time+3),tailX:520,tailY:235};scene.bubbles.push(b);selectedBubbleId=b.id;changed();syncBubbles()});on("#deleteBubble","click",()=>{if(!selectedBubbleId)return;scene.bubbles=scene.bubbles.filter(b=>b.id!==selectedBubbleId);selectedBubbleId=null;changed();syncBubbles()});
on("#bubbleText","input",e=>{const b=selectedBubble();if(b){b.text=e.target.value;changed()}});on("#bubbleStyle","change",e=>{const b=selectedBubble();if(b){b.style=e.target.value;changed()}});on("#bubbleStart","change",e=>{const b=selectedBubble();if(b){b.startTime=Math.max(0,Number(e.target.value)||0);changed()}});on("#bubbleEnd","change",e=>{const b=selectedBubble();if(b){b.endTime=Math.min(scene.duration,Number(e.target.value)||scene.duration);changed()}});

on("#scrubber","input",e=>{playing=false;editPreview=null;time=Number(e.target.value);render();syncBackgroundUI();syncBubbles()});function playTick(now){if(!playing)return;time+=(now-lastFrame)/1000;lastFrame=now;if(time>=scene.duration){time=scene.duration;playing=false}render();if(playing)requestAnimationFrame(playTick)}on("#play","click",()=>{editPreview=null;if(time>=scene.duration)time=0;playing=true;lastFrame=performance.now();requestAnimationFrame(playTick)});on("#stop","click",()=>{playing=false;time=0;editPreview=null;render()});

const videoCanvas=$("#videoStage"),videoCtx=videoCanvas.getContext("2d");let videoPlaying=false,videoTime=0,videoLast=0,recorder=null,chunks=[];
const totalDuration=()=>project.scenes.reduce((n,s)=>n+s.duration,0);function sceneAtGlobal(t){let off=0;for(let i=0;i<project.scenes.length;i++){const s=project.scenes[i];if(t<=off+s.duration||i===project.scenes.length-1)return{scene:s,index:i,local:Math.max(0,t-off),offset:off};off+=s.duration}return{scene:project.scenes[0],index:0,local:0,offset:0}}
function renderVideo(){const at=sceneAtGlobal(videoTime),s=at.scene;renderScene(videoCtx,s,at.local,{selectable:false});const tr=s.transition||{type:"cut",duration:.35},d=Math.max(.05,tr.duration||.35);if(tr.type==="fade"){let a=0;if(at.local<d)a=1-at.local/d;else if(s.duration-at.local<d)a=1-(s.duration-at.local)/d;if(a>0){videoCtx.fillStyle="rgba(0,0,0,"+Math.max(0,Math.min(1,a))+")";videoCtx.fillRect(0,0,videoCanvas.width,videoCanvas.height)}}setText("#videoCaption",s.caption||"");setText("#videoClock",fmt(videoTime)+" / "+fmt(totalDuration()));setVal("#videoScrubber",videoTime);$("#videoScrubber").max=totalDuration();setText("#videoScript",s.script||project.scripts.sceneById[s.id]||"");$("#sceneStrip").innerHTML=project.scenes.map((x,i)=>'<button class="'+(i===at.index?"active":"")+'" data-vscene="'+i+'">'+(i+1)+'. '+esc(x.name)+'</button>').join("");$$("[data-vscene]").forEach(b=>on(b,"click",()=>{videoTime=project.scenes.slice(0,Number(b.dataset.vscene)).reduce((n,s)=>n+s.duration,0);renderVideo()}))}
function videoTick(now){if(!videoPlaying)return;videoTime+=(now-videoLast)/1000;videoLast=now;if(videoTime>=totalDuration()){videoTime=totalDuration();videoPlaying=false}renderVideo();if(videoPlaying)requestAnimationFrame(videoTick)}
function setVideoMode(onMode){document.body.classList.toggle("video-mode",onMode);$("#editorMode").classList.toggle("active",!onMode);$("#videoMode").classList.toggle("active",onMode);if(onMode)renderVideo()}
on("#editorMode","click",()=>setVideoMode(false));on("#videoMode","click",()=>setVideoMode(true));on("#mobileVideo","click",()=>setVideoMode(true));on("#videoPlayPause","click",()=>{videoPlaying=!videoPlaying;if(videoPlaying){if(videoTime>=totalDuration())videoTime=0;videoLast=performance.now();requestAnimationFrame(videoTick)}});on("#videoStop","click",()=>{videoPlaying=false;videoTime=0;renderVideo()});on("#videoScrubber","input",e=>{videoPlaying=false;videoTime=Number(e.target.value);renderVideo()});on("#videoPrevScene","click",()=>{const a=sceneAtGlobal(videoTime);videoTime=Math.max(0,a.offset-.01);videoTime=sceneAtGlobal(videoTime).offset;renderVideo()});on("#videoNextScene","click",()=>{const a=sceneAtGlobal(videoTime);videoTime=Math.min(totalDuration(),a.offset+a.scene.duration+.001);renderVideo()});
on("#recordVideo","click",()=>{if(recorder?.state==="recording"){recorder.stop();return}if(!videoCanvas.captureStream||!window.MediaRecorder)return alert("This browser cannot record the canvas.");chunks=[];const stream=videoCanvas.captureStream(project.fps||30),mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm";recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:"video/webm"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(project.name||"mep-video")+".webm";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setText("#recordVideo","Record WebM")};recorder.start();setText("#recordVideo","Stop Recording");videoTime=0;videoPlaying=true;videoLast=performance.now();requestAnimationFrame(videoTick)});

let buddyPets=Number(localStorage.getItem("mep-buddy-pets")||0),buddyPetting=false,buddyMoved=false,buddyTimer=null,lastPetAt=0;
function buddyBounds(){const size=58,pad=12,bottom=window.innerWidth<=760?88:18;return{minX:pad,maxX:Math.max(pad,window.innerWidth-size-pad),minY:72,maxY:Math.max(80,window.innerHeight-size-bottom)}}
function moveBuddy(immediate=false){const a=$("#helperAvatar");if(!a)return;if($("#helperPanel")?.classList.contains("open")){clearTimeout(buddyTimer);buddyTimer=setTimeout(()=>moveBuddy(false),3500);return}const b=buddyBounds(),x=Math.round(b.minX+Math.random()*(b.maxX-b.minX)),y=Math.round(b.minY+Math.random()*(b.maxY-b.minY));a.style.left=x+"px";a.style.top=y+"px";a.style.right="auto";a.style.bottom="auto";a.style.transition=immediate?"none":"left 2.8s ease-in-out, top 2.8s ease-in-out, transform .2s ease";if($("#helperPanel").classList.contains("open"))positionBuddyPanel();clearTimeout(buddyTimer);buddyTimer=setTimeout(()=>moveBuddy(false),4500+Math.random()*4500)}
function positionBuddyPanel(){const a=$("#helperAvatar"),p=$("#helperPanel");if(!a||!p)return;const r=a.getBoundingClientRect(),w=Math.min(330,window.innerWidth-24),left=Math.max(12,Math.min(window.innerWidth-w-12,r.left+r.width/2-w/2)),above=r.top>360;p.style.width=w+"px";p.style.left=left+"px";p.style.right="auto";p.style.top=above?Math.max(12,r.top-330)+"px":Math.min(window.innerHeight-350,r.bottom+10)+"px";p.style.bottom="auto"}
function petBuddy(){const now=Date.now();if(now-lastPetAt<260)return;lastPetAt=now;buddyPets++;localStorage.setItem("mep-buddy-pets",buddyPets);setText("#petCount","Pets: "+buddyPets);setText("#helperFace",buddyPets%5===0?"^▽^":"•ᴗ•");const a=$("#helperAvatar"),h=$("#petHeart");a.classList.remove("petted");void a.offsetWidth;a.classList.add("petted");h.classList.remove("show");void h.offsetWidth;h.classList.add("show");setText("#helperStatus",buddyPets%5===0?"Very happy!":"Petted ♥");setTimeout(()=>{setText("#helperFace","•‿•");setText("#helperStatus",cloudReady?"Firestore synced":"Floating around")},1100)}
on("#helperAvatar","click",()=>{if(buddyMoved){buddyMoved=false;return}$("#helperPanel").classList.toggle("open");positionBuddyPanel()});on("#helperAvatar","pointerenter",e=>{if(e.pointerType==="mouse")petBuddy()});on("#helperAvatar","pointerdown",e=>{buddyPetting=true;buddyMoved=false;$("#helperAvatar").setPointerCapture?.(e.pointerId)});on("#helperAvatar","pointermove",e=>{if(!buddyPetting)return;buddyMoved=true;petBuddy()});on("#helperAvatar","pointerup",()=>{buddyPetting=false});on("#closeHelper","click",()=>$("#helperPanel").classList.remove("open"));$$("[data-jump]").forEach(b=>on(b,"click",()=>{document.querySelector(b.dataset.jump)?.scrollIntoView({behavior:"smooth",block:"start"});$("#helperPanel").classList.remove("open")}));on("#helperAddCountry","click",()=>{addPreset("unionSquare");$("#helperPanel").classList.remove("open")});on("#helperAddBackgroundKey","click",()=>{addBackgroundKey();$("#helperPanel").classList.remove("open")});on("#helperVideoMode","click",()=>{setVideoMode(true);$("#helperPanel").classList.remove("open")});on("#helperOpenAI","click",()=>$("#aiDialog").showModal());on(window,"resize",()=>{const a=$("#helperAvatar"),r=a?.getBoundingClientRect();if(r&&r.right>window.innerWidth)moveBuddy(true)});setText("#petCount","Pets: "+buddyPets);setTimeout(()=>moveBuddy(true),700);

on("#aiShowContext","click",()=>{$("#aiJson").value=JSON.stringify(MEPAIDirector.promptPackage($("#aiPrompt").value,project),null,2)});on("#aiGenerate","click",async()=>{try{setText("#aiStatus","Generating…");const plan=await MEPAIDirector.generate($("#aiPrompt").value.trim(),project);$("#aiJson").value=JSON.stringify(plan,null,2);setText("#aiStatus","Plan ready")}catch(e){setText("#aiStatus",e.message)}});on("#aiApply","click",()=>{try{project=MEPAIDirector.apply(JSON.parse($("#aiJson").value));scene=MEPModel.activeScene(project);selectedId=scene.characters[0]?.id||null;time=0;changed();syncUI();$("#aiDialog").close()}catch(e){setText("#aiStatus",e.message)}});

try{syncUI()}catch(e){console.error(e);$("#bootStatus").className="bootStatus error";setText("#bootStatus","MEP startup error: "+e.message)}
MEPStorage.initCloud().then(async r=>{if(!r.ok){setText("#saveStatus","Local only");$("#bootStatus").className="bootStatus warn";setText("#bootStatus","MEP works locally · Firestore unavailable");return}try{await MEPStorage.seedLibrary(MEPModel.librarySnapshot());cloudReady=true;setText("#saveStatus","Firestore ✓");if(!hadLocal){const latest=await MEPStorage.loadLatestCloud();if(latest){project=latest;scene=MEPModel.activeScene(project);selectedId=scene.characters[0]?.id||null;time=0;syncUI()}}}catch(e){console.warn(e);cloudReady=false;setText("#saveStatus","Firestore blocked");$("#bootStatus").className="bootStatus warn";setText("#bootStatus","MEP works locally · publish the Firestore MEP rules to enable cloud JSON sync")}})

window.MEP_DEBUG={get project(){return project},get scene(){return scene},render,syncUI};
})();