window.MEPCharacterStudio=(()=>{
let canvas,ctx,tool="brush",drawing=false,last=null,lasso=[],image=null;
function init(el){canvas=el;ctx=canvas.getContext("2d",{willReadFrequently:true});clear();bind()}
function clear(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#ddd";ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function bind(){canvas.onpointerdown=e=>{drawing=true;last=point(e);if(tool==="lasso"){lasso=[last]}};canvas.onpointermove=e=>{if(!drawing)return;const p=point(e);if(tool==="brush"){ctx.strokeStyle=document.querySelector("#studioColor").value;ctx.lineWidth=+document.querySelector("#studioSize").value;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}else if(tool==="eraser"){ctx.strokeStyle="#fff";ctx.lineWidth=+document.querySelector("#studioSize").value*2;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}else if(tool==="lasso"){lasso.push(p);redrawOverlay()}};canvas.onpointerup=()=>{drawing=false;if(tool==="lasso"&&lasso.length>2)extractLasso()}}
function redrawOverlay(){if(!image)image=ctx.getImageData(0,0,canvas.width,canvas.height);ctx.putImageData(image,0,0);ctx.strokeStyle="#ffb020";ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.beginPath();lasso.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([])}
function setTool(t){tool=t;if(t!=="lasso")image=null}
async function loadFile(file){const bmp=await createImageBitmap(file);clear();const scale=Math.min(canvas.width/bmp.width,canvas.height/bmp.height);const w=bmp.width*scale,h=bmp.height*scale;ctx.drawImage(bmp,(canvas.width-w)/2,(canvas.height-h)/2,w,h);image=null}
function extractLasso(){if(!image)image=ctx.getImageData(0,0,canvas.width,canvas.height);const xs=lasso.map(p=>p.x),ys=lasso.map(p=>p.y),minX=Math.max(0,Math.floor(Math.min(...xs))),maxX=Math.min(canvas.width,Math.ceil(Math.max(...xs))),minY=Math.max(0,Math.floor(Math.min(...ys))),maxY=Math.min(canvas.height,Math.ceil(Math.max(...ys))),w=maxX-minX,h=maxY-minY;if(w<2||h<2)return;ctx.putImageData(image,0,0);const src=ctx.getImageData(minX,minY,w,h),out=document.createElement("canvas");out.width=w;out.height=h;const o=out.getContext("2d"),data=src.data;function inside(x,y){let yes=false;for(let i=0,j=lasso.length-1;i<lasso.length;j=i++){const a=lasso[i],b=lasso[j];if(((a.y>y)!==(b.y>y))&&(x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x))yes=!yes}return yes}for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(!inside(x+minX,y+minY))data[(y*w+x)*4+3]=0;o.putImageData(src,0,0);window.MEP_STUDIO_STICKER=out.toDataURL("image/png");document.querySelector("#studioStatus").textContent="Sticker cutout ready ("+w+"×"+h+"). It can now be saved as a custom sprite/rig layer.";image=null;lasso=[]}
function exportPNG(){const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download="mep-character-art.png";a.click()}
return{init,clear,setTool,loadFile,exportPNG,getSticker:()=>window.MEP_STUDIO_STICKER||null};
})();