window.MEPRenderer=(()=>{
const rad=d=>d*Math.PI/180;
function end(p,len,ang,face=1){return{x:p.x+Math.sin(rad(ang))*face,y:p.y+Math.cos(rad(ang))}}
function geometry(s){const sc=s.scale,face=s.facing,p=s.pose,style=MEPModel.BODY_STYLES?.[s.bodyStyle]||MEPModel.BODY_STYLES?.historyCutout||{length:1},len=style.length||1,hip={x:s.x,y:s.y},shoulder=end(hip,-100*sc,p.torso,face),neck=end(shoulder,-22*sc,p.torso,face),head=end(neck,-38*sc,p.head+p.torso,face),la1=end(shoulder,70*sc,p.leftUpperArm-110,face),la2=end(la1,65*sc,p.leftUpperArm+p.leftLowerArm-110,face),ra1=end(shoulder,70*sc,p.rightUpperArm+110,face),ra2=end(ra1,65*sc,p.rightUpperArm+p.rightLowerArm+110,face),ll1=end(hip,82*sc,p.leftUpperLeg-15,face),ll2=end(ll1,78*sc,p.leftUpperLeg+p.leftLowerLeg-8,face),rl1=end(hip,82*sc,p.rightUpperLeg+15,face),rl2=end(rl1,78*sc,p.rightUpperLeg+p.rightLowerLeg+8,face);return{hip,shoulder,neck,head,leftElbow:la1,leftHand:la2,rightElbow:ra1,rightHand:ra2,leftKnee:ll1,leftFoot:ll2,rightKnee:rl1,rightFoot:rl2}}
function limb(ctx,a,b,w,color){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.lineWidth=w;ctx.lineCap="round";ctx.stroke()}
function circle(ctx,p,r,fill,stroke="#242424",sw=3){ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=sw;ctx.stroke()}
function hat(ctx,g,sc,rig,face){ctx.save();ctx.translate(g.head.x,g.head.y-28*sc);ctx.fillStyle=rig.hair||"#34261e";ctx.strokeStyle=rig.line||"#242424";ctx.lineWidth=3*sc;if(rig.hat==="crown"){ctx.beginPath();ctx.moveTo(-25*sc,0);ctx.lineTo(-22*sc,-25*sc);ctx.lineTo(-8*sc,-12*sc);ctx.lineTo(0,-29*sc);ctx.lineTo(10*sc,-12*sc);ctx.lineTo(24*sc,-25*sc);ctx.lineTo(25*sc,0);ctx.closePath();ctx.fillStyle="#e6b83f";ctx.fill();ctx.stroke()}else if(rig.hat==="helmet"){ctx.beginPath();ctx.arc(0,0,29*sc,Math.PI,Math.PI*2);ctx.lineTo(31*sc,2*sc);ctx.lineTo(-31*sc,2*sc);ctx.closePath();ctx.fillStyle="#59654c";ctx.fill();ctx.stroke()}else if(rig.hat==="officer"){ctx.fillStyle="#35455a";ctx.fillRect(-28*sc,-13*sc,56*sc,16*sc);ctx.fillRect(-19*sc,-25*sc,38*sc,15*sc);ctx.strokeRect(-28*sc,-13*sc,56*sc,16*sc)}else if(rig.hat==="tricorn"){ctx.beginPath();ctx.moveTo(-32*sc,0);ctx.lineTo(0,-22*sc);ctx.lineTo(32*sc,0);ctx.lineTo(0,-7*sc);ctx.closePath();ctx.fillStyle="#3a302a";ctx.fill();ctx.stroke()}ctx.restore()}
function hair(ctx,g,sc,rig){if(rig.hat&&rig.hat!=="none")return;ctx.beginPath();ctx.arc(g.head.x,g.head.y-5*sc,31*sc,Math.PI*1.05,Math.PI*1.95);ctx.strokeStyle=rig.hair||"#34261e";ctx.lineWidth=(rig.hairStyle==="messy"?12:9)*sc;ctx.stroke()}
function prop(ctx,g,sc,rig,face){const p=rig.prop||"none";if(p==="none")return;const hand=g.rightHand;ctx.save();ctx.translate(hand.x,hand.y);ctx.scale(face,1);ctx.strokeStyle="#302820";ctx.fillStyle="#65513b";ctx.lineCap="round";if(["spear","staff","rifle","musket"].includes(p)){ctx.lineWidth=(p==="rifle"||p==="musket"?8:5)*sc;ctx.beginPath();ctx.moveTo(-8*sc,18*sc);ctx.lineTo(15*sc,-85*sc);ctx.stroke();if(p==="spear"){ctx.fillStyle="#aaa";ctx.beginPath();ctx.moveTo(15*sc,-85*sc);ctx.lineTo(8*sc,-65*sc);ctx.lineTo(23*sc,-68*sc);ctx.closePath();ctx.fill()}}else if(p==="sword"){ctx.lineWidth=5*sc;ctx.strokeStyle="#bfc4c8";ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(20*sc,-70*sc);ctx.stroke();ctx.strokeStyle="#6a4a2d";ctx.lineWidth=8*sc;ctx.beginPath();ctx.moveTo(-8*sc,-3*sc);ctx.lineTo(9*sc,4*sc);ctx.stroke()}else if(p==="bow"){ctx.strokeStyle="#6a4a2d";ctx.lineWidth=4*sc;ctx.beginPath();ctx.arc(0,-30*sc,35*sc,-1.1,1.1);ctx.stroke()}else if(p==="axe"){ctx.strokeStyle="#6a4a2d";ctx.lineWidth=6*sc;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(15*sc,-58*sc);ctx.stroke();ctx.fillStyle="#8b8f92";ctx.fillRect(8*sc,-65*sc,24*sc,14*sc)}else if(p==="torch"){ctx.strokeStyle="#6a4a2d";ctx.lineWidth=6*sc;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(10*sc,-55*sc);ctx.stroke();ctx.fillStyle="#e77722";ctx.beginPath();ctx.arc(11*sc,-65*sc,12*sc,0,Math.PI*2);ctx.fill()}ctx.restore()}
function draw(ctx,s,selected=false,rig={}){s={...s,bodyStyle:rig.bodyStyle||"historyCutout"};const g=geometry(s),sc=s.scale,style=MEPModel.BODY_STYLES?.[rig.bodyStyle]||MEPModel.BODY_STYLES?.historyCutout||{},tw=style.torsoWidth||1,lw=style.limbWidth||1,line=rig.line||"#242424",skin=rig.skin||"#f2c7a5",shirt=rig.shirt||"#58667a",pants=rig.pants||"#343a46";
 limb(ctx,g.hip,g.shoulder,31*sc*tw,shirt);limb(ctx,g.shoulder,g.leftElbow,16*sc*lw,shirt);limb(ctx,g.leftElbow,g.leftHand,13*sc*lw,skin);limb(ctx,g.shoulder,g.rightElbow,16*sc*lw,shirt);limb(ctx,g.rightElbow,g.rightHand,13*sc*lw,skin);limb(ctx,g.hip,g.leftKnee,19*sc*lw,pants);limb(ctx,g.leftKnee,g.leftFoot,16*sc*lw,pants);limb(ctx,g.hip,g.rightKnee,19*sc*lw,pants);limb(ctx,g.rightKnee,g.rightFoot,16*sc*lw,pants);
 circle(ctx,g.leftHand,8*sc,skin,line,2*sc);circle(ctx,g.rightHand,8*sc,skin,line,2*sc);
 ctx.fillStyle=line;[g.leftFoot,g.rightFoot].forEach(f=>{ctx.beginPath();ctx.ellipse(f.x+8*sc*s.facing,f.y,16*sc,7*sc,0,0,Math.PI*2);ctx.fill()});
 circle(ctx,g.head,33*sc*(rig.headScale||1)*(style.headScale||1),skin,line,4*sc);hair(ctx,g,sc,rig);hat(ctx,g,sc,rig,s.facing);
 const eyeX=g.head.x+11*sc*s.facing;circle(ctx,{x:eyeX,y:g.head.y-4*sc},3*sc,"#222","#222",1);ctx.strokeStyle=line;ctx.lineWidth=2*sc;ctx.beginPath();if(rig.expression==="angry"){ctx.moveTo(g.head.x+2*sc*s.facing,g.head.y-14*sc);ctx.lineTo(g.head.x+19*sc*s.facing,g.head.y-9*sc)}else if(rig.expression==="sad"){ctx.arc(g.head.x+13*sc*s.facing,g.head.y+17*sc,9*sc,1.15*Math.PI,1.85*Math.PI)}else if(rig.expression==="happy"){ctx.arc(g.head.x+13*sc*s.facing,g.head.y+5*sc,10*sc,.15*Math.PI,.85*Math.PI)}else{ctx.moveTo(g.head.x+4*sc*s.facing,g.head.y+11*sc);ctx.lineTo(g.head.x+20*sc*s.facing,g.head.y+10*sc)}ctx.stroke();prop(ctx,g,sc,rig,s.facing);
 if(rig.accessory==="tie"){ctx.fillStyle="#9a2d31";ctx.beginPath();ctx.moveTo(g.shoulder.x,g.shoulder.y+6*sc);ctx.lineTo(g.shoulder.x-6*sc,g.shoulder.y+34*sc);ctx.lineTo(g.shoulder.x,g.shoulder.y+46*sc);ctx.lineTo(g.shoulder.x+6*sc,g.shoulder.y+34*sc);ctx.closePath();ctx.fill()}if(rig.accessory==="sash"){ctx.strokeStyle="#d9b447";ctx.lineWidth=8*sc;ctx.beginPath();ctx.moveTo(g.shoulder.x-15*sc,g.shoulder.y);ctx.lineTo(g.hip.x+18*sc,g.hip.y);ctx.stroke()}
 if(selected){Object.values(g).forEach(pt=>circle(ctx,pt,5,"#ffb020","#fff",1));ctx.strokeStyle="#ffb020";ctx.lineWidth=2;ctx.setLineDash([6,5]);ctx.strokeRect(g.hip.x-58*sc,g.head.y-55*sc,116*sc,(g.hip.y-g.head.y)+205*sc);ctx.setLineDash([])}return g}
function drawScenery(ctx,bgKey,w,h){if(bgKey==="countryside"||bgKey==="battlefield"){const sky=ctx.createLinearGradient(0,0,0,h*.75);sky.addColorStop(0,"#b8d4e6");sky.addColorStop(1,"#f2c890");ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle=bgKey==="battlefield"?"#73735e":"#789263";for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(0,h*(.52+i*.06));for(let x=0;x<=w;x+=80)ctx.lineTo(x,h*(.5+i*.06)+Math.sin(x*.012+i)*25);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill()}ctx.fillStyle="#394a38";for(let x=35;x<w;x+=150){ctx.fillRect(x,h*.45,9,95);ctx.beginPath();ctx.arc(x+4,h*.43,42,0,Math.PI*2);ctx.fill()}}else if(bgKey==="palace"){ctx.fillStyle="#eadfcf";ctx.fillRect(0,0,w,h);ctx.fillStyle="#b89a77";for(let x=80;x<w;x+=190)ctx.fillRect(x,80,42,h-150);ctx.fillStyle="#6f3e3e";ctx.fillRect(0,0,w,65);ctx.fillStyle="#9b795d";ctx.fillRect(0,h*.79,w,h*.21)}else if(bgKey==="city"){ctx.fillStyle="#b9ceda";ctx.fillRect(0,0,w,h);for(let x=0;x<w;x+=130){const bh=180+(x%260);ctx.fillStyle=x%260?"#777f84":"#8c8177";ctx.fillRect(x,h-bh,115,bh);ctx.fillStyle="#d8c66d";for(let y=h-bh+30;y<h-30;y+=45)for(let q=x+20;q<x+100;q+=38)ctx.fillRect(q,y,17,22)}}}
function drawBackground(ctx,bgKey,w=1280,h=720){const bg=MEPModel.BACKGROUNDS[bgKey]||MEPModel.BACKGROUNDS.parchment;if(["countryside","battlefield","palace","city"].includes(bgKey))drawScenery(ctx,bgKey,w,h);else{ctx.fillStyle=bg.fill;ctx.fillRect(0,0,w,h);ctx.fillStyle=bg.ground;ctx.fillRect(0,570,w,150);}if(bg.kind==="map"){ctx.fillStyle="#748f66";const blobs=[[.18,.36,.12,.18],[.35,.3,.09,.12],[.49,.29,.13,.11],[.58,.39,.17,.16],[.72,.32,.12,.2],[.84,.54,.1,.1],[.3,.58,.08,.18]];blobs.forEach(([x,y,rx,ry])=>{ctx.beginPath();ctx.ellipse(w*x,h*y,w*rx,h*ry,0,0,Math.PI*2);ctx.fill()});ctx.fillStyle="#ffffffaa";ctx.font="bold 34px system-ui";ctx.fillText(bg.name,34,52)}}
function roundRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawBubble(ctx,b){
 const st=MEPModel.BUBBLE_STYLES[b.style]||MEPModel.BUBBLE_STYLES.speech,x=b.x||300,y=b.y||120,w=b.width||300,h=b.height||100,r=st.radius||10;
 ctx.save();ctx.fillStyle=b.fill||st.fill;ctx.strokeStyle=b.stroke||st.stroke;ctx.lineWidth=b.strokeWidth||3;
 if(st.tail==="burst"){ctx.beginPath();const cx=x+w/2,cy=y+h/2;for(let i=0;i<24;i++){const a=Math.PI*2*i/24,rr=i%2?Math.min(w,h)*.54:Math.min(w,h)*.66,px=cx+Math.cos(a)*rr*1.55,py=cy+Math.sin(a)*rr*.65;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();ctx.stroke()}
 else{roundRect(ctx,x,y,w,h,r);ctx.fill();ctx.stroke();if(st.tail==="speech"){ctx.beginPath();const tx=b.tailX??x+w*.25,ty=b.tailY??y+h+42;ctx.moveTo(x+w*.2,y+h-2);ctx.lineTo(tx,ty);ctx.lineTo(x+w*.36,y+h-2);ctx.closePath();ctx.fill();ctx.stroke()}else if(st.tail==="thought"){for(let i=0;i<3;i++){ctx.beginPath();ctx.arc((b.tailX??x+w*.2)+i*15,(b.tailY??y+h+40)-i*12,6+i*2,0,Math.PI*2);ctx.fill();ctx.stroke()}}}
 ctx.fillStyle=b.textColor||st.text;ctx.font=(b.bold?"700 ":"600 ")+(b.fontSize||28)+"px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";
 const words=String(b.text||"Type dialogue").split(/\s+/),lines=[];let line="";for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>w-30&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);const lh=(b.fontSize||28)*1.15,start=y+h/2-(lines.length-1)*lh/2;lines.forEach((ln,i)=>ctx.fillText(ln,x+w/2,start+i*lh,w-24));ctx.restore()
}

return{draw,geometry,drawBackground,drawBubble};
})();